export const CanvasSkin = (params) => {
  const skinItem = params.item;

  const DropperIcon = (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      shapeRendering="crispEdges"
      version="1.1"
      viewBox="0 0 144 256"
      className="h-8"
    >
      <g transform="scale(16 16)">
        <rect fill="#F8FAFC" x="0" y="0" height="1" width="1" />
        <rect fill="#F8FAFC" x="1" y="0" height="1" width="1" />
        <rect fill="#0e5fe8" x="2" y="0" height="1" width="1" />
        <rect fill="#0e5fe8" x="3" y="0" height="1" width="1" />
        <rect fill="#0e5fe8" x="4" y="0" height="1" width="1" />
        <rect fill="#0e5fe8" x="5" y="0" height="1" width="1" />
        <rect fill="#F8FAFC" x="6" y="0" height="1" width="1" />
        <rect fill="#F8FAFC" x="7" y="0" height="1" width="1" />
        <rect fill="#F8FAFC" x="8" y="0" height="1" width="1" />
        <rect fill="#F8FAFC" x="0" y="1" height="1" width="1" />
        <rect fill="#F8FAFC" x="1" y="1" height="1" width="1" />
        <rect fill="#0e5fe8" x="2" y="1" height="1" width="1" />
        <rect fill="#F8FAFC" x="3" y="1" height="1" width="1" />
        <rect fill="#F8FAFC" x="4" y="1" height="1" width="1" />
        <rect fill="#0e5fe8" x="5" y="1" height="1" width="1" />
        <rect fill="#F8FAFC" x="6" y="1" height="1" width="1" />
        <rect fill="#F8FAFC" x="7" y="1" height="1" width="1" />
        <rect fill="#F8FAFC" x="8" y="1" height="1" width="1" />
        <rect fill="#0e5fe8" x="0" y="2" height="1" width="1" />
        <rect fill="#0e5fe8" x="1" y="2" height="1" width="1" />
        <rect fill="#0e5fe8" x="2" y="2" height="1" width="1" />
        <rect fill="#F8FAFC" x="3" y="2" height="1" width="1" />
        <rect fill="#F8FAFC" x="4" y="2" height="1" width="1" />
        <rect fill="#0e5fe8" x="5" y="2" height="1" width="1" />
        <rect fill="#0e5fe8" x="6" y="2" height="1" width="1" />
        <rect fill="#0e5fe8" x="7" y="2" height="1" width="1" />
        <rect fill="#F8FAFC" x="8" y="2" height="1" width="1" />
        <rect fill="#F8FAFC" x="0" y="3" height="1" width="1" />
        <rect fill="#0e5fe8" x="1" y="3" height="1" width="1" />
        <rect fill="#F8FAFC" x="2" y="3" height="1" width="1" />
        <rect fill="#F8FAFC" x="3" y="3" height="1" width="1" />
        <rect fill="#F8FAFC" x="4" y="3" height="1" width="1" />
        <rect fill="#F8FAFC" x="5" y="3" height="1" width="1" />
        <rect fill="#0e5fe8" x="6" y="3" height="1" width="1" />
        <rect fill="#F8FAFC" x="7" y="3" height="1" width="1" />
        <rect fill="#F8FAFC" x="8" y="3" height="1" width="1" />
        <rect fill="#F8FAFC" x="0" y="4" height="1" width="1" />
        <rect fill="#0e5fe8" x="1" y="4" height="1" width="1" />
        <rect fill="#0e5fe8" x="2" y="4" height="1" width="1" />
        <rect fill="#0e5fe8" x="3" y="4" height="1" width="1" />
        <rect fill="#0e5fe8" x="4" y="4" height="1" width="1" />
        <rect fill="#0e5fe8" x="5" y="4" height="1" width="1" />
        <rect fill="#0e5fe8" x="6" y="4" height="1" width="1" />
        <rect fill="#F8FAFC" x="7" y="4" height="1" width="1" />
        <rect fill="#F8FAFC" x="8" y="4" height="1" width="1" />
        <rect fill="#F8FAFC" x="0" y="5" height="1" width="1" />
        <rect fill="#0e5fe8" x="1" y="5" height="1" width="1" />
        <rect fill="#F8FAFC" x="2" y="5" height="1" width="1" />
        <rect fill="#F8FAFC" x="3" y="5" height="1" width="1" />
        <rect fill="#F8FAFC" x="4" y="5" height="1" width="1" />
        <rect fill="#F8FAFC" x="5" y="5" height="1" width="1" />
        <rect fill="#0e5fe8" x="6" y="5" height="1" width="1" />
        <rect fill="#F8FAFC" x="7" y="5" height="1" width="1" />
        <rect fill="#F8FAFC" x="8" y="5" height="1" width="1" />
        <rect fill="#F8FAFC" x="0" y="6" height="1" width="1" />
        <rect fill="#0e5fe8" x="1" y="6" height="1" width="1" />
        <rect fill="#F8FAFC" x="2" y="6" height="1" width="1" />
        <rect fill="#F8FAFC" x="3" y="6" height="1" width="1" />
        <rect fill="#F8FAFC" x="4" y="6" height="1" width="1" />
        <rect fill="#F8FAFC" x="5" y="6" height="1" width="1" />
        <rect fill="#0e5fe8" x="6" y="6" height="1" width="1" />
        <rect fill="#F8FAFC" x="7" y="6" height="1" width="1" />
        <rect fill="#F8FAFC" x="8" y="6" height="1" width="1" />
        <rect fill="#F8FAFC" x="0" y="7" height="1" width="1" />
        <rect fill="#0e5fe8" x="1" y="7" height="1" width="1" />
        <rect fill="#F8FAFC" x="2" y="7" height="1" width="1" />
        <rect fill="#F8FAFC" x="3" y="7" height="1" width="1" />
        <rect fill="#F8FAFC" x="4" y="7" height="1" width="1" />
        <rect fill="#F8FAFC" x="5" y="7" height="1" width="1" />
        <rect fill="#0e5fe8" x="6" y="7" height="1" width="1" />
        <rect fill="#F8FAFC" x="7" y="7" height="1" width="1" />
        <rect fill="#F8FAFC" x="8" y="7" height="1" width="1" />
        <rect fill="#F8FAFC" x="0" y="8" height="1" width="1" />
        <rect fill="#0e5fe8" x="1" y="8" height="1" width="1" />
        <rect fill="#F8FAFC" x="2" y="8" height="1" width="1" />
        <rect fill="#F8FAFC" x="3" y="8" height="1" width="1" />
        <rect fill="#F8FAFC" x="4" y="8" height="1" width="1" />
        <rect fill="#F8FAFC" x="5" y="8" height="1" width="1" />
        <rect fill="#0e5fe8" x="6" y="8" height="1" width="1" />
        <rect fill="#F8FAFC" x="7" y="8" height="1" width="1" />
        <rect fill="#F8FAFC" x="8" y="8" height="1" width="1" />
        <rect fill="#F8FAFC" x="0" y="9" height="1" width="1" />
        <rect fill="#0e5fe8" x="1" y="9" height="1" width="1" />
        <rect fill="#F8FAFC" x="2" y="9" height="1" width="1" />
        <rect fill="#F8FAFC" x="3" y="9" height="1" width="1" />
        <rect fill="#F8FAFC" x="4" y="9" height="1" width="1" />
        <rect fill="#F8FAFC" x="5" y="9" height="1" width="1" />
        <rect fill="#0e5fe8" x="6" y="9" height="1" width="1" />
        <rect fill="#F8FAFC" x="7" y="9" height="1" width="1" />
        <rect fill="#F8FAFC" x="8" y="9" height="1" width="1" />
        <rect fill="#F8FAFC" x="0" y="10" height="1" width="1" />
        <rect fill="#0e5fe8" x="1" y="10" height="1" width="1" />
        <rect fill="#F8FAFC" x="2" y="10" height="1" width="1" />
        <rect fill="#F8FAFC" x="3" y="10" height="1" width="1" />
        <rect fill="#F8FAFC" x="4" y="10" height="1" width="1" />
        <rect fill="#F8FAFC" x="5" y="10" height="1" width="1" />
        <rect fill="#0e5fe8" x="6" y="10" height="1" width="1" />
        <rect fill="#F8FAFC" x="7" y="10" height="1" width="1" />
        <rect fill="#F8FAFC" x="8" y="10" height="1" width="1" />
        <rect fill="#F8FAFC" x="0" y="11" height="1" width="1" />
        <rect fill="#0e5fe8" x="1" y="11" height="1" width="1" />
        <rect fill="#0e5fe8" x="2" y="11" height="1" width="1" />
        <rect fill="#F8FAFC" x="3" y="11" height="1" width="1" />
        <rect fill="#F8FAFC" x="4" y="11" height="1" width="1" />
        <rect fill="#0e5fe8" x="5" y="11" height="1" width="1" />
        <rect fill="#0e5fe8" x="6" y="11" height="1" width="1" />
        <rect fill="#F8FAFC" x="7" y="11" height="1" width="1" />
        <rect fill="#F8FAFC" x="8" y="11" height="1" width="1" />
        <rect fill="#F8FAFC" x="0" y="12" height="1" width="1" />
        <rect fill="#F8FAFC" x="1" y="12" height="1" width="1" />
        <rect fill="#0e5fe8" x="2" y="12" height="1" width="1" />
        <rect fill="#F8FAFC" x="3" y="12" height="1" width="1" />
        <rect fill="#F8FAFC" x="4" y="12" height="1" width="1" />
        <rect fill="#0e5fe8" x="5" y="12" height="1" width="1" />
        <rect fill="#F8FAFC" x="6" y="12" height="1" width="1" />
        <rect fill="#F8FAFC" x="7" y="12" height="1" width="1" />
        <rect fill="#F8FAFC" x="8" y="12" height="1" width="1" />
        <rect fill="#F8FAFC" x="0" y="13" height="1" width="1" />
        <rect fill="#F8FAFC" x="1" y="13" height="1" width="1" />
        <rect fill="#F8FAFC" x="2" y="13" height="1" width="1" />
        <rect fill="#0e5fe8" x="3" y="13" height="1" width="1" />
        <rect fill="#0e5fe8" x="4" y="13" height="1" width="1" />
        <rect fill="#F8FAFC" x="5" y="13" height="1" width="1" />
        <rect fill="#F8FAFC" x="6" y="13" height="1" width="1" />
        <rect fill="#F8FAFC" x="7" y="13" height="1" width="1" />
        <rect fill="#F8FAFC" x="8" y="13" height="1" width="1" />
        <rect fill="#F8FAFC" x="0" y="14" height="1" width="1" />
        <rect fill="#F8FAFC" x="1" y="14" height="1" width="1" />
        <rect fill="#F8FAFC" x="2" y="14" height="1" width="1" />
        <rect fill="#F8FAFC" x="3" y="14" height="1" width="1" />
        <rect fill="#F8FAFC" x="4" y="14" height="1" width="1" />
        <rect fill="#F8FAFC" x="5" y="14" height="1" width="1" />
        <rect fill="#F8FAFC" x="6" y="14" height="1" width="1" />
        <rect fill="#F8FAFC" x="7" y="14" height="1" width="1" />
        <rect fill="#F8FAFC" x="8" y="14" height="1" width="1" />
        <rect fill="#F8FAFC" x="0" y="15" height="1" width="1" />
        <rect fill="#F8FAFC" x="1" y="15" height="1" width="1" />
        <rect fill="#F8FAFC" x="2" y="15" height="1" width="1" />
        <rect fill="#F8FAFC" x="3" y="15" height="1" width="1" />
        <rect fill="#F8FAFC" x="4" y="15" height="1" width="1" />
        <rect fill="#F8FAFC" x="5" y="15" height="1" width="1" />
        <rect fill="#F8FAFC" x="6" y="15" height="1" width="1" />
        <rect fill="#F8FAFC" x="7" y="15" height="1" width="1" />
        <rect fill="#F8FAFC" x="8" y="15" height="1" width="1" />
      </g>
    </svg>
  );
  const DropperIconActive = (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      shapeRendering="crispEdges"
      version="1.1"
      viewBox="0 0 144 256"
      className="h-8"
    >
      <g transform="scale(16 16)">
        <rect fill="#6effff" x="0" y="0" height="1" width="1" />
        <rect fill="#6effff" x="1" y="0" height="1" width="1" />
        <rect fill="#2b74f4" x="2" y="0" height="1" width="1" />
        <rect fill="#2b74f4" x="3" y="0" height="1" width="1" />
        <rect fill="#2b74f4" x="4" y="0" height="1" width="1" />
        <rect fill="#2b74f4" x="5" y="0" height="1" width="1" />
        <rect fill="#6effff" x="6" y="0" height="1" width="1" />
        <rect fill="#6effff" x="7" y="0" height="1" width="1" />
        <rect fill="#6effff" x="8" y="0" height="1" width="1" />
        <rect fill="#6effff" x="0" y="1" height="1" width="1" />
        <rect fill="#6effff" x="1" y="1" height="1" width="1" />
        <rect fill="#2b74f4" x="2" y="1" height="1" width="1" />
        <rect fill="#6effff" x="3" y="1" height="1" width="1" />
        <rect fill="#6effff" x="4" y="1" height="1" width="1" />
        <rect fill="#2b74f4" x="5" y="1" height="1" width="1" />
        <rect fill="#6effff" x="6" y="1" height="1" width="1" />
        <rect fill="#6effff" x="7" y="1" height="1" width="1" />
        <rect fill="#6effff" x="8" y="1" height="1" width="1" />
        <rect fill="#2b74f4" x="0" y="2" height="1" width="1" />
        <rect fill="#2b74f4" x="1" y="2" height="1" width="1" />
        <rect fill="#2b74f4" x="2" y="2" height="1" width="1" />
        <rect fill="#6effff" x="3" y="2" height="1" width="1" />
        <rect fill="#6effff" x="4" y="2" height="1" width="1" />
        <rect fill="#2b74f4" x="5" y="2" height="1" width="1" />
        <rect fill="#2b74f4" x="6" y="2" height="1" width="1" />
        <rect fill="#2b74f4" x="7" y="2" height="1" width="1" />
        <rect fill="#6effff" x="8" y="2" height="1" width="1" />
        <rect fill="#6effff" x="0" y="3" height="1" width="1" />
        <rect fill="#2b74f4" x="1" y="3" height="1" width="1" />
        <rect fill="#6effff" x="2" y="3" height="1" width="1" />
        <rect fill="#6effff" x="3" y="3" height="1" width="1" />
        <rect fill="#6effff" x="4" y="3" height="1" width="1" />
        <rect fill="#6effff" x="5" y="3" height="1" width="1" />
        <rect fill="#2b74f4" x="6" y="3" height="1" width="1" />
        <rect fill="#6effff" x="7" y="3" height="1" width="1" />
        <rect fill="#6effff" x="8" y="3" height="1" width="1" />
        <rect fill="#6effff" x="0" y="4" height="1" width="1" />
        <rect fill="#2b74f4" x="1" y="4" height="1" width="1" />
        <rect fill="#2b74f4" x="2" y="4" height="1" width="1" />
        <rect fill="#2b74f4" x="3" y="4" height="1" width="1" />
        <rect fill="#2b74f4" x="4" y="4" height="1" width="1" />
        <rect fill="#2b74f4" x="5" y="4" height="1" width="1" />
        <rect fill="#2b74f4" x="6" y="4" height="1" width="1" />
        <rect fill="#6effff" x="7" y="4" height="1" width="1" />
        <rect fill="#6effff" x="8" y="4" height="1" width="1" />
        <rect fill="#6effff" x="0" y="5" height="1" width="1" />
        <rect fill="#2b74f4" x="1" y="5" height="1" width="1" />
        <rect fill="#6effff" x="2" y="5" height="1" width="1" />
        <rect fill="#6effff" x="3" y="5" height="1" width="1" />
        <rect fill="#6effff" x="4" y="5" height="1" width="1" />
        <rect fill="#6effff" x="5" y="5" height="1" width="1" />
        <rect fill="#2b74f4" x="6" y="5" height="1" width="1" />
        <rect fill="#6effff" x="7" y="5" height="1" width="1" />
        <rect fill="#6effff" x="8" y="5" height="1" width="1" />
        <rect fill="#6effff" x="0" y="6" height="1" width="1" />
        <rect fill="#2b74f4" x="1" y="6" height="1" width="1" />
        <rect fill="#6effff" x="2" y="6" height="1" width="1" />
        <rect fill="#6effff" x="3" y="6" height="1" width="1" />
        <rect fill="#6effff" x="4" y="6" height="1" width="1" />
        <rect fill="#6effff" x="5" y="6" height="1" width="1" />
        <rect fill="#2b74f4" x="6" y="6" height="1" width="1" />
        <rect fill="#6effff" x="7" y="6" height="1" width="1" />
        <rect fill="#6effff" x="8" y="6" height="1" width="1" />
        <rect fill="#6effff" x="0" y="7" height="1" width="1" />
        <rect fill="#2b74f4" x="1" y="7" height="1" width="1" />
        <rect fill="#6effff" x="2" y="7" height="1" width="1" />
        <rect fill="#6effff" x="3" y="7" height="1" width="1" />
        <rect fill="#6effff" x="4" y="7" height="1" width="1" />
        <rect fill="#6effff" x="5" y="7" height="1" width="1" />
        <rect fill="#2b74f4" x="6" y="7" height="1" width="1" />
        <rect fill="#6effff" x="7" y="7" height="1" width="1" />
        <rect fill="#6effff" x="8" y="7" height="1" width="1" />
        <rect fill="#6effff" x="0" y="8" height="1" width="1" />
        <rect fill="#2b74f4" x="1" y="8" height="1" width="1" />
        <rect fill="#6effff" x="2" y="8" height="1" width="1" />
        <rect fill="#6effff" x="3" y="8" height="1" width="1" />
        <rect fill="#6effff" x="4" y="8" height="1" width="1" />
        <rect fill="#6effff" x="5" y="8" height="1" width="1" />
        <rect fill="#2b74f4" x="6" y="8" height="1" width="1" />
        <rect fill="#6effff" x="7" y="8" height="1" width="1" />
        <rect fill="#6effff" x="8" y="8" height="1" width="1" />
        <rect fill="#6effff" x="0" y="9" height="1" width="1" />
        <rect fill="#2b74f4" x="1" y="9" height="1" width="1" />
        <rect fill="#6effff" x="2" y="9" height="1" width="1" />
        <rect fill="#6effff" x="3" y="9" height="1" width="1" />
        <rect fill="#6effff" x="4" y="9" height="1" width="1" />
        <rect fill="#6effff" x="5" y="9" height="1" width="1" />
        <rect fill="#2b74f4" x="6" y="9" height="1" width="1" />
        <rect fill="#6effff" x="7" y="9" height="1" width="1" />
        <rect fill="#6effff" x="8" y="9" height="1" width="1" />
        <rect fill="#6effff" x="0" y="10" height="1" width="1" />
        <rect fill="#2b74f4" x="1" y="10" height="1" width="1" />
        <rect fill="#6effff" x="2" y="10" height="1" width="1" />
        <rect fill="#6effff" x="3" y="10" height="1" width="1" />
        <rect fill="#6effff" x="4" y="10" height="1" width="1" />
        <rect fill="#6effff" x="5" y="10" height="1" width="1" />
        <rect fill="#2b74f4" x="6" y="10" height="1" width="1" />
        <rect fill="#6effff" x="7" y="10" height="1" width="1" />
        <rect fill="#6effff" x="8" y="10" height="1" width="1" />
        <rect fill="#6effff" x="0" y="11" height="1" width="1" />
        <rect fill="#2b74f4" x="1" y="11" height="1" width="1" />
        <rect fill="#2b74f4" x="2" y="11" height="1" width="1" />
        <rect fill="#6effff" x="3" y="11" height="1" width="1" />
        <rect fill="#6effff" x="4" y="11" height="1" width="1" />
        <rect fill="#2b74f4" x="5" y="11" height="1" width="1" />
        <rect fill="#2b74f4" x="6" y="11" height="1" width="1" />
        <rect fill="#6effff" x="7" y="11" height="1" width="1" />
        <rect fill="#6effff" x="8" y="11" height="1" width="1" />
        <rect fill="#6effff" x="0" y="12" height="1" width="1" />
        <rect fill="#6effff" x="1" y="12" height="1" width="1" />
        <rect fill="#2b74f4" x="2" y="12" height="1" width="1" />
        <rect fill="#6effff" x="3" y="12" height="1" width="1" />
        <rect fill="#6effff" x="4" y="12" height="1" width="1" />
        <rect fill="#2b74f4" x="5" y="12" height="1" width="1" />
        <rect fill="#6effff" x="6" y="12" height="1" width="1" />
        <rect fill="#6effff" x="7" y="12" height="1" width="1" />
        <rect fill="#6effff" x="8" y="12" height="1" width="1" />
        <rect fill="#6effff" x="0" y="13" height="1" width="1" />
        <rect fill="#6effff" x="1" y="13" height="1" width="1" />
        <rect fill="#6effff" x="2" y="13" height="1" width="1" />
        <rect fill="#2b74f4" x="3" y="13" height="1" width="1" />
        <rect fill="#2b74f4" x="4" y="13" height="1" width="1" />
        <rect fill="#6effff" x="5" y="13" height="1" width="1" />
        <rect fill="#6effff" x="6" y="13" height="1" width="1" />
        <rect fill="#6effff" x="7" y="13" height="1" width="1" />
        <rect fill="#6effff" x="8" y="13" height="1" width="1" />
        <rect fill="#6effff" x="0" y="14" height="1" width="1" />
        <rect fill="#6effff" x="1" y="14" height="1" width="1" />
        <rect fill="#6effff" x="2" y="14" height="1" width="1" />
        <rect fill="#6effff" x="3" y="14" height="1" width="1" />
        <rect fill="#6effff" x="4" y="14" height="1" width="1" />
        <rect fill="#6effff" x="5" y="14" height="1" width="1" />
        <rect fill="#6effff" x="6" y="14" height="1" width="1" />
        <rect fill="#6effff" x="7" y="14" height="1" width="1" />
        <rect fill="#6effff" x="8" y="14" height="1" width="1" />
        <rect fill="#6effff" x="0" y="15" height="1" width="1" />
        <rect fill="#6effff" x="1" y="15" height="1" width="1" />
        <rect fill="#6effff" x="2" y="15" height="1" width="1" />
        <rect fill="#6effff" x="3" y="15" height="1" width="1" />
        <rect fill="#6effff" x="4" y="15" height="1" width="1" />
        <rect fill="#6effff" x="5" y="15" height="1" width="1" />
        <rect fill="#6effff" x="6" y="15" height="1" width="1" />
        <rect fill="#6effff" x="7" y="15" height="1" width="1" />
        <rect fill="#6effff" x="8" y="15" height="1" width="1" />
      </g>
    </svg>
  );

  const MoveUpIcon = (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      shapeRendering="crispEdges"
      version="1.1"
      viewBox="0 0 256 256"
      className="h-8"
    >
      <g transform="scale(16 16)">
        <rect fill="#F8FAFC" x="0" y="0" height="1" width="1" />
        <rect fill="#F8FAFC" x="1" y="0" height="1" width="1" />
        <rect fill="#F8FAFC" x="2" y="0" height="1" width="1" />
        <rect fill="#F8FAFC" x="3" y="0" height="1" width="1" />
        <rect fill="#F8FAFC" x="4" y="0" height="1" width="1" />
        <rect fill="#F8FAFC" x="5" y="0" height="1" width="1" />
        <rect fill="#F8FAFC" x="6" y="0" height="1" width="1" />
        <rect fill="#F8FAFC" x="7" y="0" height="1" width="1" />
        <rect fill="#F8FAFC" x="8" y="0" height="1" width="1" />
        <rect fill="#F8FAFC" x="9" y="0" height="1" width="1" />
        <rect fill="#F8FAFC" x="10" y="0" height="1" width="1" />
        <rect fill="#F8FAFC" x="11" y="0" height="1" width="1" />
        <rect fill="#F8FAFC" x="12" y="0" height="1" width="1" />
        <rect fill="#F8FAFC" x="13" y="0" height="1" width="1" />
        <rect fill="#F8FAFC" x="14" y="0" height="1" width="1" />
        <rect fill="#F8FAFC" x="15" y="0" height="1" width="1" />
        <rect fill="#F8FAFC" x="0" y="1" height="1" width="1" />
        <rect fill="#F8FAFC" x="1" y="1" height="1" width="1" />
        <rect fill="#F8FAFC" x="2" y="1" height="1" width="1" />
        <rect fill="#F8FAFC" x="3" y="1" height="1" width="1" />
        <rect fill="#F8FAFC" x="4" y="1" height="1" width="1" />
        <rect fill="#F8FAFC" x="5" y="1" height="1" width="1" />
        <rect fill="#F8FAFC" x="6" y="1" height="1" width="1" />
        <rect fill="#F8FAFC" x="7" y="1" height="1" width="1" />
        <rect fill="#0EA5E9" x="8" y="1" height="1" width="1" />
        <rect fill="#F8FAFC" x="9" y="1" height="1" width="1" />
        <rect fill="#F8FAFC" x="10" y="1" height="1" width="1" />
        <rect fill="#F8FAFC" x="11" y="1" height="1" width="1" />
        <rect fill="#F8FAFC" x="12" y="1" height="1" width="1" />
        <rect fill="#F8FAFC" x="13" y="1" height="1" width="1" />
        <rect fill="#F8FAFC" x="14" y="1" height="1" width="1" />
        <rect fill="#F8FAFC" x="15" y="1" height="1" width="1" />
        <rect fill="#F8FAFC" x="0" y="2" height="1" width="1" />
        <rect fill="#F8FAFC" x="1" y="2" height="1" width="1" />
        <rect fill="#F8FAFC" x="2" y="2" height="1" width="1" />
        <rect fill="#F8FAFC" x="3" y="2" height="1" width="1" />
        <rect fill="#F8FAFC" x="4" y="2" height="1" width="1" />
        <rect fill="#F8FAFC" x="5" y="2" height="1" width="1" />
        <rect fill="#F8FAFC" x="6" y="2" height="1" width="1" />
        <rect fill="#0EA5E9" x="7" y="2" height="1" width="1" />
        <rect fill="#0EA5E9" x="8" y="2" height="1" width="1" />
        <rect fill="#0EA5E9" x="9" y="2" height="1" width="1" />
        <rect fill="#F8FAFC" x="10" y="2" height="1" width="1" />
        <rect fill="#F8FAFC" x="11" y="2" height="1" width="1" />
        <rect fill="#F8FAFC" x="12" y="2" height="1" width="1" />
        <rect fill="#F8FAFC" x="13" y="2" height="1" width="1" />
        <rect fill="#F8FAFC" x="14" y="2" height="1" width="1" />
        <rect fill="#F8FAFC" x="15" y="2" height="1" width="1" />
        <rect fill="#F8FAFC" x="0" y="3" height="1" width="1" />
        <rect fill="#F8FAFC" x="1" y="3" height="1" width="1" />
        <rect fill="#F8FAFC" x="2" y="3" height="1" width="1" />
        <rect fill="#F8FAFC" x="3" y="3" height="1" width="1" />
        <rect fill="#F8FAFC" x="4" y="3" height="1" width="1" />
        <rect fill="#F8FAFC" x="5" y="3" height="1" width="1" />
        <rect fill="#0EA5E9" x="6" y="3" height="1" width="1" />
        <rect fill="#0EA5E9" x="7" y="3" height="1" width="1" />
        <rect fill="#0EA5E9" x="8" y="3" height="1" width="1" />
        <rect fill="#0EA5E9" x="9" y="3" height="1" width="1" />
        <rect fill="#0EA5E9" x="10" y="3" height="1" width="1" />
        <rect fill="#F8FAFC" x="11" y="3" height="1" width="1" />
        <rect fill="#F8FAFC" x="12" y="3" height="1" width="1" />
        <rect fill="#F8FAFC" x="13" y="3" height="1" width="1" />
        <rect fill="#F8FAFC" x="14" y="3" height="1" width="1" />
        <rect fill="#F8FAFC" x="15" y="3" height="1" width="1" />
        <rect fill="#F8FAFC" x="0" y="4" height="1" width="1" />
        <rect fill="#F8FAFC" x="1" y="4" height="1" width="1" />
        <rect fill="#F8FAFC" x="2" y="4" height="1" width="1" />
        <rect fill="#F8FAFC" x="3" y="4" height="1" width="1" />
        <rect fill="#F8FAFC" x="4" y="4" height="1" width="1" />
        <rect fill="#0EA5E9" x="5" y="4" height="1" width="1" />
        <rect fill="#0EA5E9" x="6" y="4" height="1" width="1" />
        <rect fill="#F8FAFC" x="7" y="4" height="1" width="1" />
        <rect fill="#F8FAFC" x="8" y="4" height="1" width="1" />
        <rect fill="#F8FAFC" x="9" y="4" height="1" width="1" />
        <rect fill="#0EA5E9" x="10" y="4" height="1" width="1" />
        <rect fill="#0EA5E9" x="11" y="4" height="1" width="1" />
        <rect fill="#F8FAFC" x="12" y="4" height="1" width="1" />
        <rect fill="#F8FAFC" x="13" y="4" height="1" width="1" />
        <rect fill="#F8FAFC" x="14" y="4" height="1" width="1" />
        <rect fill="#F8FAFC" x="15" y="4" height="1" width="1" />
        <rect fill="#F8FAFC" x="0" y="5" height="1" width="1" />
        <rect fill="#F8FAFC" x="1" y="5" height="1" width="1" />
        <rect fill="#F8FAFC" x="2" y="5" height="1" width="1" />
        <rect fill="#F8FAFC" x="3" y="5" height="1" width="1" />
        <rect fill="#0EA5E9" x="4" y="5" height="1" width="1" />
        <rect fill="#0EA5E9" x="5" y="5" height="1" width="1" />
        <rect fill="#F8FAFC" x="6" y="5" height="1" width="1" />
        <rect fill="#F8FAFC" x="7" y="5" height="1" width="1" />
        <rect fill="#F8FAFC" x="8" y="5" height="1" width="1" />
        <rect fill="#F8FAFC" x="9" y="5" height="1" width="1" />
        <rect fill="#F8FAFC" x="10" y="5" height="1" width="1" />
        <rect fill="#0EA5E9" x="11" y="5" height="1" width="1" />
        <rect fill="#0EA5E9" x="12" y="5" height="1" width="1" />
        <rect fill="#F8FAFC" x="13" y="5" height="1" width="1" />
        <rect fill="#F8FAFC" x="14" y="5" height="1" width="1" />
        <rect fill="#F8FAFC" x="15" y="5" height="1" width="1" />
        <rect fill="#F8FAFC" x="0" y="6" height="1" width="1" />
        <rect fill="#F8FAFC" x="1" y="6" height="1" width="1" />
        <rect fill="#F8FAFC" x="2" y="6" height="1" width="1" />
        <rect fill="#0EA5E9" x="3" y="6" height="1" width="1" />
        <rect fill="#0EA5E9" x="4" y="6" height="1" width="1" />
        <rect fill="#F8FAFC" x="5" y="6" height="1" width="1" />
        <rect fill="#F8FAFC" x="6" y="6" height="1" width="1" />
        <rect fill="#F8FAFC" x="7" y="6" height="1" width="1" />
        <rect fill="#F8FAFC" x="8" y="6" height="1" width="1" />
        <rect fill="#F8FAFC" x="9" y="6" height="1" width="1" />
        <rect fill="#F8FAFC" x="10" y="6" height="1" width="1" />
        <rect fill="#F8FAFC" x="11" y="6" height="1" width="1" />
        <rect fill="#0EA5E9" x="12" y="6" height="1" width="1" />
        <rect fill="#F8FAFC" x="13" y="6" height="1" width="1" />
        <rect fill="#F8FAFC" x="14" y="6" height="1" width="1" />
        <rect fill="#F8FAFC" x="15" y="6" height="1" width="1" />
        <rect fill="#F8FAFC" x="0" y="7" height="1" width="1" />
        <rect fill="#F8FAFC" x="1" y="7" height="1" width="1" />
        <rect fill="#0EA5E9" x="2" y="7" height="1" width="1" />
        <rect fill="#0EA5E9" x="3" y="7" height="1" width="1" />
        <rect fill="#F8FAFC" x="4" y="7" height="1" width="1" />
        <rect fill="#F8FAFC" x="5" y="7" height="1" width="1" />
        <rect fill="#F8FAFC" x="6" y="7" height="1" width="1" />
        <rect fill="#F8FAFC" x="7" y="7" height="1" width="1" />
        <rect fill="#F8FAFC" x="8" y="7" height="1" width="1" />
        <rect fill="#F8FAFC" x="9" y="7" height="1" width="1" />
        <rect fill="#F8FAFC" x="10" y="7" height="1" width="1" />
        <rect fill="#F8FAFC" x="11" y="7" height="1" width="1" />
        <rect fill="#0EA5E9" x="12" y="7" height="1" width="1" />
        <rect fill="#0EA5E9" x="13" y="7" height="1" width="1" />
        <rect fill="#F8FAFC" x="14" y="7" height="1" width="1" />
        <rect fill="#F8FAFC" x="15" y="7" height="1" width="1" />
        <rect fill="#F8FAFC" x="0" y="8" height="1" width="1" />
        <rect fill="#0EA5E9" x="1" y="8" height="1" width="1" />
        <rect fill="#0EA5E9" x="2" y="8" height="1" width="1" />
        <rect fill="#F8FAFC" x="3" y="8" height="1" width="1" />
        <rect fill="#F8FAFC" x="4" y="8" height="1" width="1" />
        <rect fill="#F8FAFC" x="5" y="8" height="1" width="1" />
        <rect fill="#F8FAFC" x="6" y="8" height="1" width="1" />
        <rect fill="#F8FAFC" x="7" y="8" height="1" width="1" />
        <rect fill="#F8FAFC" x="8" y="8" height="1" width="1" />
        <rect fill="#F8FAFC" x="9" y="8" height="1" width="1" />
        <rect fill="#F8FAFC" x="10" y="8" height="1" width="1" />
        <rect fill="#F8FAFC" x="11" y="8" height="1" width="1" />
        <rect fill="#F8FAFC" x="12" y="8" height="1" width="1" />
        <rect fill="#0EA5E9" x="13" y="8" height="1" width="1" />
        <rect fill="#0EA5E9" x="14" y="8" height="1" width="1" />
        <rect fill="#F8FAFC" x="15" y="8" height="1" width="1" />
        <rect fill="#F8FAFC" x="0" y="9" height="1" width="1" />
        <rect fill="#0EA5E9" x="1" y="9" height="1" width="1" />
        <rect fill="#F8FAFC" x="2" y="9" height="1" width="1" />
        <rect fill="#F8FAFC" x="3" y="9" height="1" width="1" />
        <rect fill="#F8FAFC" x="4" y="9" height="1" width="1" />
        <rect fill="#F8FAFC" x="5" y="9" height="1" width="1" />
        <rect fill="#F8FAFC" x="6" y="9" height="1" width="1" />
        <rect fill="#F8FAFC" x="7" y="9" height="1" width="1" />
        <rect fill="#F8FAFC" x="8" y="9" height="1" width="1" />
        <rect fill="#F8FAFC" x="9" y="9" height="1" width="1" />
        <rect fill="#F8FAFC" x="10" y="9" height="1" width="1" />
        <rect fill="#F8FAFC" x="11" y="9" height="1" width="1" />
        <rect fill="#F8FAFC" x="12" y="9" height="1" width="1" />
        <rect fill="#F8FAFC" x="13" y="9" height="1" width="1" />
        <rect fill="#0EA5E9" x="14" y="9" height="1" width="1" />
        <rect fill="#F8FAFC" x="15" y="9" height="1" width="1" />
        <rect fill="#F8FAFC" x="0" y="10" height="1" width="1" />
        <rect fill="#F8FAFC" x="1" y="10" height="1" width="1" />
        <rect fill="#F8FAFC" x="2" y="10" height="1" width="1" />
        <rect fill="#F8FAFC" x="3" y="10" height="1" width="1" />
        <rect fill="#F8FAFC" x="4" y="10" height="1" width="1" />
        <rect fill="#F8FAFC" x="5" y="10" height="1" width="1" />
        <rect fill="#F8FAFC" x="6" y="10" height="1" width="1" />
        <rect fill="#F8FAFC" x="7" y="10" height="1" width="1" />
        <rect fill="#F8FAFC" x="8" y="10" height="1" width="1" />
        <rect fill="#F8FAFC" x="9" y="10" height="1" width="1" />
        <rect fill="#F8FAFC" x="10" y="10" height="1" width="1" />
        <rect fill="#F8FAFC" x="11" y="10" height="1" width="1" />
        <rect fill="#F8FAFC" x="12" y="10" height="1" width="1" />
        <rect fill="#F8FAFC" x="13" y="10" height="1" width="1" />
        <rect fill="#F8FAFC" x="14" y="10" height="1" width="1" />
        <rect fill="#F8FAFC" x="15" y="10" height="1" width="1" />
        <rect fill="#F8FAFC" x="0" y="11" height="1" width="1" />
        <rect fill="#F8FAFC" x="1" y="11" height="1" width="1" />
        <rect fill="#F8FAFC" x="2" y="11" height="1" width="1" />
        <rect fill="#F8FAFC" x="3" y="11" height="1" width="1" />
        <rect fill="#F8FAFC" x="4" y="11" height="1" width="1" />
        <rect fill="#F8FAFC" x="5" y="11" height="1" width="1" />
        <rect fill="#F8FAFC" x="6" y="11" height="1" width="1" />
        <rect fill="#F8FAFC" x="7" y="11" height="1" width="1" />
        <rect fill="#F8FAFC" x="8" y="11" height="1" width="1" />
        <rect fill="#F8FAFC" x="9" y="11" height="1" width="1" />
        <rect fill="#F8FAFC" x="10" y="11" height="1" width="1" />
        <rect fill="#F8FAFC" x="11" y="11" height="1" width="1" />
        <rect fill="#F8FAFC" x="12" y="11" height="1" width="1" />
        <rect fill="#F8FAFC" x="13" y="11" height="1" width="1" />
        <rect fill="#F8FAFC" x="14" y="11" height="1" width="1" />
        <rect fill="#F8FAFC" x="15" y="11" height="1" width="1" />
        <rect fill="#F8FAFC" x="0" y="12" height="1" width="1" />
        <rect fill="#F8FAFC" x="1" y="12" height="1" width="1" />
        <rect fill="#F8FAFC" x="2" y="12" height="1" width="1" />
        <rect fill="#F8FAFC" x="3" y="12" height="1" width="1" />
        <rect fill="#F8FAFC" x="4" y="12" height="1" width="1" />
        <rect fill="#F8FAFC" x="5" y="12" height="1" width="1" />
        <rect fill="#F8FAFC" x="6" y="12" height="1" width="1" />
        <rect fill="#F8FAFC" x="7" y="12" height="1" width="1" />
        <rect fill="#F8FAFC" x="8" y="12" height="1" width="1" />
        <rect fill="#F8FAFC" x="9" y="12" height="1" width="1" />
        <rect fill="#F8FAFC" x="10" y="12" height="1" width="1" />
        <rect fill="#F8FAFC" x="11" y="12" height="1" width="1" />
        <rect fill="#F8FAFC" x="12" y="12" height="1" width="1" />
        <rect fill="#F8FAFC" x="13" y="12" height="1" width="1" />
        <rect fill="#F8FAFC" x="14" y="12" height="1" width="1" />
        <rect fill="#F8FAFC" x="15" y="12" height="1" width="1" />
        <rect fill="#F8FAFC" x="0" y="13" height="1" width="1" />
        <rect fill="#F8FAFC" x="1" y="13" height="1" width="1" />
        <rect fill="#F8FAFC" x="2" y="13" height="1" width="1" />
        <rect fill="#F8FAFC" x="3" y="13" height="1" width="1" />
        <rect fill="#F8FAFC" x="4" y="13" height="1" width="1" />
        <rect fill="#F8FAFC" x="5" y="13" height="1" width="1" />
        <rect fill="#F8FAFC" x="6" y="13" height="1" width="1" />
        <rect fill="#F8FAFC" x="7" y="13" height="1" width="1" />
        <rect fill="#F8FAFC" x="8" y="13" height="1" width="1" />
        <rect fill="#F8FAFC" x="9" y="13" height="1" width="1" />
        <rect fill="#F8FAFC" x="10" y="13" height="1" width="1" />
        <rect fill="#F8FAFC" x="11" y="13" height="1" width="1" />
        <rect fill="#F8FAFC" x="12" y="13" height="1" width="1" />
        <rect fill="#F8FAFC" x="13" y="13" height="1" width="1" />
        <rect fill="#F8FAFC" x="14" y="13" height="1" width="1" />
        <rect fill="#F8FAFC" x="15" y="13" height="1" width="1" />
        <rect fill="#F8FAFC" x="0" y="14" height="1" width="1" />
        <rect fill="#F8FAFC" x="1" y="14" height="1" width="1" />
        <rect fill="#F8FAFC" x="2" y="14" height="1" width="1" />
        <rect fill="#F8FAFC" x="3" y="14" height="1" width="1" />
        <rect fill="#F8FAFC" x="4" y="14" height="1" width="1" />
        <rect fill="#F8FAFC" x="5" y="14" height="1" width="1" />
        <rect fill="#F8FAFC" x="6" y="14" height="1" width="1" />
        <rect fill="#F8FAFC" x="7" y="14" height="1" width="1" />
        <rect fill="#F8FAFC" x="8" y="14" height="1" width="1" />
        <rect fill="#F8FAFC" x="9" y="14" height="1" width="1" />
        <rect fill="#F8FAFC" x="10" y="14" height="1" width="1" />
        <rect fill="#F8FAFC" x="11" y="14" height="1" width="1" />
        <rect fill="#F8FAFC" x="12" y="14" height="1" width="1" />
        <rect fill="#F8FAFC" x="13" y="14" height="1" width="1" />
        <rect fill="#F8FAFC" x="14" y="14" height="1" width="1" />
        <rect fill="#F8FAFC" x="15" y="14" height="1" width="1" />
        <rect fill="#F8FAFC" x="0" y="15" height="1" width="1" />
        <rect fill="#F8FAFC" x="1" y="15" height="1" width="1" />
        <rect fill="#F8FAFC" x="2" y="15" height="1" width="1" />
        <rect fill="#F8FAFC" x="3" y="15" height="1" width="1" />
        <rect fill="#F8FAFC" x="4" y="15" height="1" width="1" />
        <rect fill="#F8FAFC" x="5" y="15" height="1" width="1" />
        <rect fill="#F8FAFC" x="6" y="15" height="1" width="1" />
        <rect fill="#F8FAFC" x="7" y="15" height="1" width="1" />
        <rect fill="#F8FAFC" x="8" y="15" height="1" width="1" />
        <rect fill="#F8FAFC" x="9" y="15" height="1" width="1" />
        <rect fill="#F8FAFC" x="10" y="15" height="1" width="1" />
        <rect fill="#F8FAFC" x="11" y="15" height="1" width="1" />
        <rect fill="#F8FAFC" x="12" y="15" height="1" width="1" />
        <rect fill="#F8FAFC" x="13" y="15" height="1" width="1" />
        <rect fill="#F8FAFC" x="14" y="15" height="1" width="1" />
        <rect fill="#F8FAFC" x="15" y="15" height="1" width="1" />
      </g>
    </svg>
  );

  const MoveDownIcon = (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      shapeRendering="crispEdges"
      version="1.1"
      viewBox="0 0 256 256"
      className="h-8"
    >
      <g transform="scale(16 16)">
        <rect fill="#F8FAFC" x="0" y="0" height="1" width="1" />
        <rect fill="#F8FAFC" x="1" y="0" height="1" width="1" />
        <rect fill="#F8FAFC" x="2" y="0" height="1" width="1" />
        <rect fill="#F8FAFC" x="3" y="0" height="1" width="1" />
        <rect fill="#F8FAFC" x="4" y="0" height="1" width="1" />
        <rect fill="#F8FAFC" x="5" y="0" height="1" width="1" />
        <rect fill="#F8FAFC" x="6" y="0" height="1" width="1" />
        <rect fill="#F8FAFC" x="7" y="0" height="1" width="1" />
        <rect fill="#F8FAFC" x="8" y="0" height="1" width="1" />
        <rect fill="#F8FAFC" x="9" y="0" height="1" width="1" />
        <rect fill="#F8FAFC" x="10" y="0" height="1" width="1" />
        <rect fill="#F8FAFC" x="11" y="0" height="1" width="1" />
        <rect fill="#F8FAFC" x="12" y="0" height="1" width="1" />
        <rect fill="#F8FAFC" x="13" y="0" height="1" width="1" />
        <rect fill="#F8FAFC" x="14" y="0" height="1" width="1" />
        <rect fill="#F8FAFC" x="15" y="0" height="1" width="1" />
        <rect fill="#F8FAFC" x="0" y="1" height="1" width="1" />
        <rect fill="#F8FAFC" x="1" y="1" height="1" width="1" />
        <rect fill="#F8FAFC" x="2" y="1" height="1" width="1" />
        <rect fill="#F8FAFC" x="3" y="1" height="1" width="1" />
        <rect fill="#F8FAFC" x="4" y="1" height="1" width="1" />
        <rect fill="#F8FAFC" x="5" y="1" height="1" width="1" />
        <rect fill="#F8FAFC" x="6" y="1" height="1" width="1" />
        <rect fill="#F8FAFC" x="7" y="1" height="1" width="1" />
        <rect fill="#F8FAFC" x="8" y="1" height="1" width="1" />
        <rect fill="#F8FAFC" x="9" y="1" height="1" width="1" />
        <rect fill="#F8FAFC" x="10" y="1" height="1" width="1" />
        <rect fill="#F8FAFC" x="11" y="1" height="1" width="1" />
        <rect fill="#F8FAFC" x="12" y="1" height="1" width="1" />
        <rect fill="#F8FAFC" x="13" y="1" height="1" width="1" />
        <rect fill="#F8FAFC" x="14" y="1" height="1" width="1" />
        <rect fill="#F8FAFC" x="15" y="1" height="1" width="1" />
        <rect fill="#F8FAFC" x="0" y="2" height="1" width="1" />
        <rect fill="#F8FAFC" x="1" y="2" height="1" width="1" />
        <rect fill="#F8FAFC" x="2" y="2" height="1" width="1" />
        <rect fill="#F8FAFC" x="3" y="2" height="1" width="1" />
        <rect fill="#F8FAFC" x="4" y="2" height="1" width="1" />
        <rect fill="#F8FAFC" x="5" y="2" height="1" width="1" />
        <rect fill="#F8FAFC" x="6" y="2" height="1" width="1" />
        <rect fill="#F8FAFC" x="7" y="2" height="1" width="1" />
        <rect fill="#F8FAFC" x="8" y="2" height="1" width="1" />
        <rect fill="#F8FAFC" x="9" y="2" height="1" width="1" />
        <rect fill="#F8FAFC" x="10" y="2" height="1" width="1" />
        <rect fill="#F8FAFC" x="11" y="2" height="1" width="1" />
        <rect fill="#F8FAFC" x="12" y="2" height="1" width="1" />
        <rect fill="#F8FAFC" x="13" y="2" height="1" width="1" />
        <rect fill="#F8FAFC" x="14" y="2" height="1" width="1" />
        <rect fill="#F8FAFC" x="15" y="2" height="1" width="1" />
        <rect fill="#F8FAFC" x="0" y="3" height="1" width="1" />
        <rect fill="#F8FAFC" x="1" y="3" height="1" width="1" />
        <rect fill="#F8FAFC" x="2" y="3" height="1" width="1" />
        <rect fill="#F8FAFC" x="3" y="3" height="1" width="1" />
        <rect fill="#F8FAFC" x="4" y="3" height="1" width="1" />
        <rect fill="#F8FAFC" x="5" y="3" height="1" width="1" />
        <rect fill="#F8FAFC" x="6" y="3" height="1" width="1" />
        <rect fill="#F8FAFC" x="7" y="3" height="1" width="1" />
        <rect fill="#F8FAFC" x="8" y="3" height="1" width="1" />
        <rect fill="#F8FAFC" x="9" y="3" height="1" width="1" />
        <rect fill="#F8FAFC" x="10" y="3" height="1" width="1" />
        <rect fill="#F8FAFC" x="11" y="3" height="1" width="1" />
        <rect fill="#F8FAFC" x="12" y="3" height="1" width="1" />
        <rect fill="#F8FAFC" x="13" y="3" height="1" width="1" />
        <rect fill="#F8FAFC" x="14" y="3" height="1" width="1" />
        <rect fill="#F8FAFC" x="15" y="3" height="1" width="1" />
        <rect fill="#F8FAFC" x="0" y="4" height="1" width="1" />
        <rect fill="#0EA5E9" x="1" y="4" height="1" width="1" />
        <rect fill="#F8FAFC" x="2" y="4" height="1" width="1" />
        <rect fill="#F8FAFC" x="3" y="4" height="1" width="1" />
        <rect fill="#F8FAFC" x="4" y="4" height="1" width="1" />
        <rect fill="#F8FAFC" x="5" y="4" height="1" width="1" />
        <rect fill="#F8FAFC" x="6" y="4" height="1" width="1" />
        <rect fill="#F8FAFC" x="7" y="4" height="1" width="1" />
        <rect fill="#F8FAFC" x="8" y="4" height="1" width="1" />
        <rect fill="#F8FAFC" x="9" y="4" height="1" width="1" />
        <rect fill="#F8FAFC" x="10" y="4" height="1" width="1" />
        <rect fill="#F8FAFC" x="11" y="4" height="1" width="1" />
        <rect fill="#F8FAFC" x="12" y="4" height="1" width="1" />
        <rect fill="#0EA5E9" x="13" y="4" height="1" width="1" />
        <rect fill="#0EA5E9" x="14" y="4" height="1" width="1" />
        <rect fill="#F8FAFC" x="15" y="4" height="1" width="1" />
        <rect fill="#F8FAFC" x="0" y="5" height="1" width="1" />
        <rect fill="#0EA5E9" x="1" y="5" height="1" width="1" />
        <rect fill="#0EA5E9" x="2" y="5" height="1" width="1" />
        <rect fill="#F8FAFC" x="3" y="5" height="1" width="1" />
        <rect fill="#F8FAFC" x="4" y="5" height="1" width="1" />
        <rect fill="#F8FAFC" x="5" y="5" height="1" width="1" />
        <rect fill="#F8FAFC" x="6" y="5" height="1" width="1" />
        <rect fill="#F8FAFC" x="7" y="5" height="1" width="1" />
        <rect fill="#F8FAFC" x="8" y="5" height="1" width="1" />
        <rect fill="#F8FAFC" x="9" y="5" height="1" width="1" />
        <rect fill="#F8FAFC" x="10" y="5" height="1" width="1" />
        <rect fill="#F8FAFC" x="11" y="5" height="1" width="1" />
        <rect fill="#F8FAFC" x="12" y="5" height="1" width="1" />
        <rect fill="#0EA5E9" x="13" y="5" height="1" width="1" />
        <rect fill="#F8FAFC" x="14" y="5" height="1" width="1" />
        <rect fill="#F8FAFC" x="15" y="5" height="1" width="1" />
        <rect fill="#F8FAFC" x="0" y="6" height="1" width="1" />
        <rect fill="#F8FAFC" x="1" y="6" height="1" width="1" />
        <rect fill="#0EA5E9" x="2" y="6" height="1" width="1" />
        <rect fill="#0EA5E9" x="3" y="6" height="1" width="1" />
        <rect fill="#F8FAFC" x="4" y="6" height="1" width="1" />
        <rect fill="#F8FAFC" x="5" y="6" height="1" width="1" />
        <rect fill="#F8FAFC" x="6" y="6" height="1" width="1" />
        <rect fill="#F8FAFC" x="7" y="6" height="1" width="1" />
        <rect fill="#F8FAFC" x="8" y="6" height="1" width="1" />
        <rect fill="#F8FAFC" x="9" y="6" height="1" width="1" />
        <rect fill="#F8FAFC" x="10" y="6" height="1" width="1" />
        <rect fill="#F8FAFC" x="11" y="6" height="1" width="1" />
        <rect fill="#0EA5E9" x="12" y="6" height="1" width="1" />
        <rect fill="#0EA5E9" x="13" y="6" height="1" width="1" />
        <rect fill="#F8FAFC" x="14" y="6" height="1" width="1" />
        <rect fill="#F8FAFC" x="15" y="6" height="1" width="1" />
        <rect fill="#F8FAFC" x="0" y="7" height="1" width="1" />
        <rect fill="#F8FAFC" x="1" y="7" height="1" width="1" />
        <rect fill="#F8FAFC" x="2" y="7" height="1" width="1" />
        <rect fill="#0EA5E9" x="3" y="7" height="1" width="1" />
        <rect fill="#0EA5E9" x="4" y="7" height="1" width="1" />
        <rect fill="#F8FAFC" x="5" y="7" height="1" width="1" />
        <rect fill="#F8FAFC" x="6" y="7" height="1" width="1" />
        <rect fill="#F8FAFC" x="7" y="7" height="1" width="1" />
        <rect fill="#F8FAFC" x="8" y="7" height="1" width="1" />
        <rect fill="#F8FAFC" x="9" y="7" height="1" width="1" />
        <rect fill="#F8FAFC" x="10" y="7" height="1" width="1" />
        <rect fill="#F8FAFC" x="11" y="7" height="1" width="1" />
        <rect fill="#0EA5E9" x="12" y="7" height="1" width="1" />
        <rect fill="#F8FAFC" x="13" y="7" height="1" width="1" />
        <rect fill="#F8FAFC" x="14" y="7" height="1" width="1" />
        <rect fill="#F8FAFC" x="15" y="7" height="1" width="1" />
        <rect fill="#F8FAFC" x="0" y="8" height="1" width="1" />
        <rect fill="#F8FAFC" x="1" y="8" height="1" width="1" />
        <rect fill="#F8FAFC" x="2" y="8" height="1" width="1" />
        <rect fill="#F8FAFC" x="3" y="8" height="1" width="1" />
        <rect fill="#0EA5E9" x="4" y="8" height="1" width="1" />
        <rect fill="#0EA5E9" x="5" y="8" height="1" width="1" />
        <rect fill="#F8FAFC" x="6" y="8" height="1" width="1" />
        <rect fill="#F8FAFC" x="7" y="8" height="1" width="1" />
        <rect fill="#F8FAFC" x="8" y="8" height="1" width="1" />
        <rect fill="#F8FAFC" x="9" y="8" height="1" width="1" />
        <rect fill="#F8FAFC" x="10" y="8" height="1" width="1" />
        <rect fill="#0EA5E9" x="11" y="8" height="1" width="1" />
        <rect fill="#0EA5E9" x="12" y="8" height="1" width="1" />
        <rect fill="#F8FAFC" x="13" y="8" height="1" width="1" />
        <rect fill="#F8FAFC" x="14" y="8" height="1" width="1" />
        <rect fill="#F8FAFC" x="15" y="8" height="1" width="1" />
        <rect fill="#F8FAFC" x="0" y="9" height="1" width="1" />
        <rect fill="#F8FAFC" x="1" y="9" height="1" width="1" />
        <rect fill="#F8FAFC" x="2" y="9" height="1" width="1" />
        <rect fill="#F8FAFC" x="3" y="9" height="1" width="1" />
        <rect fill="#F8FAFC" x="4" y="9" height="1" width="1" />
        <rect fill="#0EA5E9" x="5" y="9" height="1" width="1" />
        <rect fill="#F8FAFC" x="6" y="9" height="1" width="1" />
        <rect fill="#F8FAFC" x="7" y="9" height="1" width="1" />
        <rect fill="#F8FAFC" x="8" y="9" height="1" width="1" />
        <rect fill="#F8FAFC" x="9" y="9" height="1" width="1" />
        <rect fill="#F8FAFC" x="10" y="9" height="1" width="1" />
        <rect fill="#0EA5E9" x="11" y="9" height="1" width="1" />
        <rect fill="#F8FAFC" x="12" y="9" height="1" width="1" />
        <rect fill="#F8FAFC" x="13" y="9" height="1" width="1" />
        <rect fill="#F8FAFC" x="14" y="9" height="1" width="1" />
        <rect fill="#F8FAFC" x="15" y="9" height="1" width="1" />
        <rect fill="#F8FAFC" x="0" y="10" height="1" width="1" />
        <rect fill="#F8FAFC" x="1" y="10" height="1" width="1" />
        <rect fill="#F8FAFC" x="2" y="10" height="1" width="1" />
        <rect fill="#F8FAFC" x="3" y="10" height="1" width="1" />
        <rect fill="#F8FAFC" x="4" y="10" height="1" width="1" />
        <rect fill="#0EA5E9" x="5" y="10" height="1" width="1" />
        <rect fill="#0EA5E9" x="6" y="10" height="1" width="1" />
        <rect fill="#F8FAFC" x="7" y="10" height="1" width="1" />
        <rect fill="#F8FAFC" x="8" y="10" height="1" width="1" />
        <rect fill="#F8FAFC" x="9" y="10" height="1" width="1" />
        <rect fill="#0EA5E9" x="10" y="10" height="1" width="1" />
        <rect fill="#0EA5E9" x="11" y="10" height="1" width="1" />
        <rect fill="#F8FAFC" x="12" y="10" height="1" width="1" />
        <rect fill="#F8FAFC" x="13" y="10" height="1" width="1" />
        <rect fill="#F8FAFC" x="14" y="10" height="1" width="1" />
        <rect fill="#F8FAFC" x="15" y="10" height="1" width="1" />
        <rect fill="#F8FAFC" x="0" y="11" height="1" width="1" />
        <rect fill="#F8FAFC" x="1" y="11" height="1" width="1" />
        <rect fill="#F8FAFC" x="2" y="11" height="1" width="1" />
        <rect fill="#F8FAFC" x="3" y="11" height="1" width="1" />
        <rect fill="#F8FAFC" x="4" y="11" height="1" width="1" />
        <rect fill="#F8FAFC" x="5" y="11" height="1" width="1" />
        <rect fill="#0EA5E9" x="6" y="11" height="1" width="1" />
        <rect fill="#F8FAFC" x="7" y="11" height="1" width="1" />
        <rect fill="#F8FAFC" x="8" y="11" height="1" width="1" />
        <rect fill="#F8FAFC" x="9" y="11" height="1" width="1" />
        <rect fill="#0EA5E9" x="10" y="11" height="1" width="1" />
        <rect fill="#F8FAFC" x="11" y="11" height="1" width="1" />
        <rect fill="#F8FAFC" x="12" y="11" height="1" width="1" />
        <rect fill="#F8FAFC" x="13" y="11" height="1" width="1" />
        <rect fill="#F8FAFC" x="14" y="11" height="1" width="1" />
        <rect fill="#F8FAFC" x="15" y="11" height="1" width="1" />
        <rect fill="#F8FAFC" x="0" y="12" height="1" width="1" />
        <rect fill="#F8FAFC" x="1" y="12" height="1" width="1" />
        <rect fill="#F8FAFC" x="2" y="12" height="1" width="1" />
        <rect fill="#F8FAFC" x="3" y="12" height="1" width="1" />
        <rect fill="#F8FAFC" x="4" y="12" height="1" width="1" />
        <rect fill="#F8FAFC" x="5" y="12" height="1" width="1" />
        <rect fill="#0EA5E9" x="6" y="12" height="1" width="1" />
        <rect fill="#0EA5E9" x="7" y="12" height="1" width="1" />
        <rect fill="#F8FAFC" x="8" y="12" height="1" width="1" />
        <rect fill="#0EA5E9" x="9" y="12" height="1" width="1" />
        <rect fill="#0EA5E9" x="10" y="12" height="1" width="1" />
        <rect fill="#F8FAFC" x="11" y="12" height="1" width="1" />
        <rect fill="#F8FAFC" x="12" y="12" height="1" width="1" />
        <rect fill="#F8FAFC" x="13" y="12" height="1" width="1" />
        <rect fill="#F8FAFC" x="14" y="12" height="1" width="1" />
        <rect fill="#F8FAFC" x="15" y="12" height="1" width="1" />
        <rect fill="#F8FAFC" x="0" y="13" height="1" width="1" />
        <rect fill="#F8FAFC" x="1" y="13" height="1" width="1" />
        <rect fill="#F8FAFC" x="2" y="13" height="1" width="1" />
        <rect fill="#F8FAFC" x="3" y="13" height="1" width="1" />
        <rect fill="#F8FAFC" x="4" y="13" height="1" width="1" />
        <rect fill="#F8FAFC" x="5" y="13" height="1" width="1" />
        <rect fill="#F8FAFC" x="6" y="13" height="1" width="1" />
        <rect fill="#0EA5E9" x="7" y="13" height="1" width="1" />
        <rect fill="#0EA5E9" x="8" y="13" height="1" width="1" />
        <rect fill="#0EA5E9" x="9" y="13" height="1" width="1" />
        <rect fill="#F8FAFC" x="10" y="13" height="1" width="1" />
        <rect fill="#F8FAFC" x="11" y="13" height="1" width="1" />
        <rect fill="#F8FAFC" x="12" y="13" height="1" width="1" />
        <rect fill="#F8FAFC" x="13" y="13" height="1" width="1" />
        <rect fill="#F8FAFC" x="14" y="13" height="1" width="1" />
        <rect fill="#F8FAFC" x="15" y="13" height="1" width="1" />
        <rect fill="#F8FAFC" x="0" y="14" height="1" width="1" />
        <rect fill="#F8FAFC" x="1" y="14" height="1" width="1" />
        <rect fill="#F8FAFC" x="2" y="14" height="1" width="1" />
        <rect fill="#F8FAFC" x="3" y="14" height="1" width="1" />
        <rect fill="#F8FAFC" x="4" y="14" height="1" width="1" />
        <rect fill="#F8FAFC" x="5" y="14" height="1" width="1" />
        <rect fill="#F8FAFC" x="6" y="14" height="1" width="1" />
        <rect fill="#F8FAFC" x="7" y="14" height="1" width="1" />
        <rect fill="#0EA5E9" x="8" y="14" height="1" width="1" />
        <rect fill="#F8FAFC" x="9" y="14" height="1" width="1" />
        <rect fill="#F8FAFC" x="10" y="14" height="1" width="1" />
        <rect fill="#F8FAFC" x="11" y="14" height="1" width="1" />
        <rect fill="#F8FAFC" x="12" y="14" height="1" width="1" />
        <rect fill="#F8FAFC" x="13" y="14" height="1" width="1" />
        <rect fill="#F8FAFC" x="14" y="14" height="1" width="1" />
        <rect fill="#F8FAFC" x="15" y="14" height="1" width="1" />
        <rect fill="#F8FAFC" x="0" y="15" height="1" width="1" />
        <rect fill="#F8FAFC" x="1" y="15" height="1" width="1" />
        <rect fill="#F8FAFC" x="2" y="15" height="1" width="1" />
        <rect fill="#F8FAFC" x="3" y="15" height="1" width="1" />
        <rect fill="#F8FAFC" x="4" y="15" height="1" width="1" />
        <rect fill="#F8FAFC" x="5" y="15" height="1" width="1" />
        <rect fill="#F8FAFC" x="6" y="15" height="1" width="1" />
        <rect fill="#F8FAFC" x="7" y="15" height="1" width="1" />
        <rect fill="#F8FAFC" x="8" y="15" height="1" width="1" />
        <rect fill="#F8FAFC" x="9" y="15" height="1" width="1" />
        <rect fill="#F8FAFC" x="10" y="15" height="1" width="1" />
        <rect fill="#F8FAFC" x="11" y="15" height="1" width="1" />
        <rect fill="#F8FAFC" x="12" y="15" height="1" width="1" />
        <rect fill="#F8FAFC" x="13" y="15" height="1" width="1" />
        <rect fill="#F8FAFC" x="14" y="15" height="1" width="1" />
        <rect fill="#F8FAFC" x="15" y="15" height="1" width="1" />
      </g>
    </svg>
  );

  const MoveRightIcon = (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      shapeRendering="crispEdges"
      version="1.1"
      viewBox="0 0 256 256"
      className="h-8"
    >
      <g transform="scale(16 16)">
        <rect fill="#F8FAFC" x="0" y="0" height="1" width="1" />
        <rect fill="#F8FAFC" x="1" y="0" height="1" width="1" />
        <rect fill="#F8FAFC" x="2" y="0" height="1" width="1" />
        <rect fill="#F8FAFC" x="3" y="0" height="1" width="1" />
        <rect fill="#F8FAFC" x="4" y="0" height="1" width="1" />
        <rect fill="#F8FAFC" x="5" y="0" height="1" width="1" />
        <rect fill="#F8FAFC" x="6" y="0" height="1" width="1" />
        <rect fill="#F8FAFC" x="7" y="0" height="1" width="1" />
        <rect fill="#F8FAFC" x="8" y="0" height="1" width="1" />
        <rect fill="#F8FAFC" x="9" y="0" height="1" width="1" />
        <rect fill="#F8FAFC" x="10" y="0" height="1" width="1" />
        <rect fill="#F8FAFC" x="11" y="0" height="1" width="1" />
        <rect fill="#F8FAFC" x="12" y="0" height="1" width="1" />
        <rect fill="#F8FAFC" x="13" y="0" height="1" width="1" />
        <rect fill="#F8FAFC" x="14" y="0" height="1" width="1" />
        <rect fill="#F8FAFC" x="15" y="0" height="1" width="1" />
        <rect fill="#F8FAFC" x="0" y="1" height="1" width="1" />
        <rect fill="#F8FAFC" x="1" y="1" height="1" width="1" />
        <rect fill="#F8FAFC" x="2" y="1" height="1" width="1" />
        <rect fill="#F8FAFC" x="3" y="1" height="1" width="1" />
        <rect fill="#F8FAFC" x="4" y="1" height="1" width="1" />
        <rect fill="#F8FAFC" x="5" y="1" height="1" width="1" />
        <rect fill="#F8FAFC" x="6" y="1" height="1" width="1" />
        <rect fill="#F8FAFC" x="7" y="1" height="1" width="1" />
        <rect fill="#F8FAFC" x="8" y="1" height="1" width="1" />
        <rect fill="#F8FAFC" x="9" y="1" height="1" width="1" />
        <rect fill="#F8FAFC" x="10" y="1" height="1" width="1" />
        <rect fill="#F8FAFC" x="11" y="1" height="1" width="1" />
        <rect fill="#F8FAFC" x="12" y="1" height="1" width="1" />
        <rect fill="#F8FAFC" x="13" y="1" height="1" width="1" />
        <rect fill="#F8FAFC" x="14" y="1" height="1" width="1" />
        <rect fill="#F8FAFC" x="15" y="1" height="1" width="1" />
        <rect fill="#F8FAFC" x="0" y="2" height="1" width="1" />
        <rect fill="#F8FAFC" x="1" y="2" height="1" width="1" />
        <rect fill="#F8FAFC" x="2" y="2" height="1" width="1" />
        <rect fill="#F8FAFC" x="3" y="2" height="1" width="1" />
        <rect fill="#F8FAFC" x="4" y="2" height="1" width="1" />
        <rect fill="#0EA5E9" x="5" y="2" height="1" width="1" />
        <rect fill="#0EA5E9" x="6" y="2" height="1" width="1" />
        <rect fill="#F8FAFC" x="7" y="2" height="1" width="1" />
        <rect fill="#F8FAFC" x="8" y="2" height="1" width="1" />
        <rect fill="#F8FAFC" x="9" y="2" height="1" width="1" />
        <rect fill="#F8FAFC" x="10" y="2" height="1" width="1" />
        <rect fill="#F8FAFC" x="11" y="2" height="1" width="1" />
        <rect fill="#F8FAFC" x="12" y="2" height="1" width="1" />
        <rect fill="#F8FAFC" x="13" y="2" height="1" width="1" />
        <rect fill="#F8FAFC" x="14" y="2" height="1" width="1" />
        <rect fill="#F8FAFC" x="15" y="2" height="1" width="1" />
        <rect fill="#F8FAFC" x="0" y="3" height="1" width="1" />
        <rect fill="#F8FAFC" x="1" y="3" height="1" width="1" />
        <rect fill="#F8FAFC" x="2" y="3" height="1" width="1" />
        <rect fill="#F8FAFC" x="3" y="3" height="1" width="1" />
        <rect fill="#F8FAFC" x="4" y="3" height="1" width="1" />
        <rect fill="#F8FAFC" x="5" y="3" height="1" width="1" />
        <rect fill="#0EA5E9" x="6" y="3" height="1" width="1" />
        <rect fill="#0EA5E9" x="7" y="3" height="1" width="1" />
        <rect fill="#0EA5E9" x="8" y="3" height="1" width="1" />
        <rect fill="#F8FAFC" x="9" y="3" height="1" width="1" />
        <rect fill="#F8FAFC" x="10" y="3" height="1" width="1" />
        <rect fill="#F8FAFC" x="11" y="3" height="1" width="1" />
        <rect fill="#F8FAFC" x="12" y="3" height="1" width="1" />
        <rect fill="#F8FAFC" x="13" y="3" height="1" width="1" />
        <rect fill="#F8FAFC" x="14" y="3" height="1" width="1" />
        <rect fill="#F8FAFC" x="15" y="3" height="1" width="1" />
        <rect fill="#F8FAFC" x="0" y="4" height="1" width="1" />
        <rect fill="#F8FAFC" x="1" y="4" height="1" width="1" />
        <rect fill="#F8FAFC" x="2" y="4" height="1" width="1" />
        <rect fill="#F8FAFC" x="3" y="4" height="1" width="1" />
        <rect fill="#F8FAFC" x="4" y="4" height="1" width="1" />
        <rect fill="#F8FAFC" x="5" y="4" height="1" width="1" />
        <rect fill="#F8FAFC" x="6" y="4" height="1" width="1" />
        <rect fill="#0EA5E9" x="7" y="4" height="1" width="1" />
        <rect fill="#0EA5E9" x="8" y="4" height="1" width="1" />
        <rect fill="#0EA5E9" x="9" y="4" height="1" width="1" />
        <rect fill="#F8FAFC" x="10" y="4" height="1" width="1" />
        <rect fill="#F8FAFC" x="11" y="4" height="1" width="1" />
        <rect fill="#F8FAFC" x="12" y="4" height="1" width="1" />
        <rect fill="#F8FAFC" x="13" y="4" height="1" width="1" />
        <rect fill="#F8FAFC" x="14" y="4" height="1" width="1" />
        <rect fill="#F8FAFC" x="15" y="4" height="1" width="1" />
        <rect fill="#F8FAFC" x="0" y="5" height="1" width="1" />
        <rect fill="#F8FAFC" x="1" y="5" height="1" width="1" />
        <rect fill="#F8FAFC" x="2" y="5" height="1" width="1" />
        <rect fill="#F8FAFC" x="3" y="5" height="1" width="1" />
        <rect fill="#F8FAFC" x="4" y="5" height="1" width="1" />
        <rect fill="#F8FAFC" x="5" y="5" height="1" width="1" />
        <rect fill="#F8FAFC" x="6" y="5" height="1" width="1" />
        <rect fill="#F8FAFC" x="7" y="5" height="1" width="1" />
        <rect fill="#F8FAFC" x="8" y="5" height="1" width="1" />
        <rect fill="#0EA5E9" x="9" y="5" height="1" width="1" />
        <rect fill="#0EA5E9" x="10" y="5" height="1" width="1" />
        <rect fill="#0EA5E9" x="11" y="5" height="1" width="1" />
        <rect fill="#F8FAFC" x="12" y="5" height="1" width="1" />
        <rect fill="#F8FAFC" x="13" y="5" height="1" width="1" />
        <rect fill="#F8FAFC" x="14" y="5" height="1" width="1" />
        <rect fill="#F8FAFC" x="15" y="5" height="1" width="1" />
        <rect fill="#F8FAFC" x="0" y="6" height="1" width="1" />
        <rect fill="#F8FAFC" x="1" y="6" height="1" width="1" />
        <rect fill="#F8FAFC" x="2" y="6" height="1" width="1" />
        <rect fill="#F8FAFC" x="3" y="6" height="1" width="1" />
        <rect fill="#F8FAFC" x="4" y="6" height="1" width="1" />
        <rect fill="#F8FAFC" x="5" y="6" height="1" width="1" />
        <rect fill="#F8FAFC" x="6" y="6" height="1" width="1" />
        <rect fill="#F8FAFC" x="7" y="6" height="1" width="1" />
        <rect fill="#F8FAFC" x="8" y="6" height="1" width="1" />
        <rect fill="#F8FAFC" x="9" y="6" height="1" width="1" />
        <rect fill="#F8FAFC" x="10" y="6" height="1" width="1" />
        <rect fill="#0EA5E9" x="11" y="6" height="1" width="1" />
        <rect fill="#0EA5E9" x="12" y="6" height="1" width="1" />
        <rect fill="#F8FAFC" x="13" y="6" height="1" width="1" />
        <rect fill="#F8FAFC" x="14" y="6" height="1" width="1" />
        <rect fill="#F8FAFC" x="15" y="6" height="1" width="1" />
        <rect fill="#F8FAFC" x="0" y="7" height="1" width="1" />
        <rect fill="#F8FAFC" x="1" y="7" height="1" width="1" />
        <rect fill="#F8FAFC" x="2" y="7" height="1" width="1" />
        <rect fill="#F8FAFC" x="3" y="7" height="1" width="1" />
        <rect fill="#F8FAFC" x="4" y="7" height="1" width="1" />
        <rect fill="#F8FAFC" x="5" y="7" height="1" width="1" />
        <rect fill="#F8FAFC" x="6" y="7" height="1" width="1" />
        <rect fill="#F8FAFC" x="7" y="7" height="1" width="1" />
        <rect fill="#F8FAFC" x="8" y="7" height="1" width="1" />
        <rect fill="#F8FAFC" x="9" y="7" height="1" width="1" />
        <rect fill="#F8FAFC" x="10" y="7" height="1" width="1" />
        <rect fill="#F8FAFC" x="11" y="7" height="1" width="1" />
        <rect fill="#0EA5E9" x="12" y="7" height="1" width="1" />
        <rect fill="#0EA5E9" x="13" y="7" height="1" width="1" />
        <rect fill="#F8FAFC" x="14" y="7" height="1" width="1" />
        <rect fill="#F8FAFC" x="15" y="7" height="1" width="1" />
        <rect fill="#F8FAFC" x="0" y="8" height="1" width="1" />
        <rect fill="#F8FAFC" x="1" y="8" height="1" width="1" />
        <rect fill="#F8FAFC" x="2" y="8" height="1" width="1" />
        <rect fill="#F8FAFC" x="3" y="8" height="1" width="1" />
        <rect fill="#F8FAFC" x="4" y="8" height="1" width="1" />
        <rect fill="#F8FAFC" x="5" y="8" height="1" width="1" />
        <rect fill="#F8FAFC" x="6" y="8" height="1" width="1" />
        <rect fill="#F8FAFC" x="7" y="8" height="1" width="1" />
        <rect fill="#F8FAFC" x="8" y="8" height="1" width="1" />
        <rect fill="#F8FAFC" x="9" y="8" height="1" width="1" />
        <rect fill="#F8FAFC" x="10" y="8" height="1" width="1" />
        <rect fill="#F8FAFC" x="11" y="8" height="1" width="1" />
        <rect fill="#0EA5E9" x="12" y="8" height="1" width="1" />
        <rect fill="#0EA5E9" x="13" y="8" height="1" width="1" />
        <rect fill="#0EA5E9" x="14" y="8" height="1" width="1" />
        <rect fill="#F8FAFC" x="15" y="8" height="1" width="1" />
        <rect fill="#F8FAFC" x="0" y="9" height="1" width="1" />
        <rect fill="#F8FAFC" x="1" y="9" height="1" width="1" />
        <rect fill="#F8FAFC" x="2" y="9" height="1" width="1" />
        <rect fill="#F8FAFC" x="3" y="9" height="1" width="1" />
        <rect fill="#F8FAFC" x="4" y="9" height="1" width="1" />
        <rect fill="#F8FAFC" x="5" y="9" height="1" width="1" />
        <rect fill="#F8FAFC" x="6" y="9" height="1" width="1" />
        <rect fill="#F8FAFC" x="7" y="9" height="1" width="1" />
        <rect fill="#F8FAFC" x="8" y="9" height="1" width="1" />
        <rect fill="#F8FAFC" x="9" y="9" height="1" width="1" />
        <rect fill="#F8FAFC" x="10" y="9" height="1" width="1" />
        <rect fill="#0EA5E9" x="11" y="9" height="1" width="1" />
        <rect fill="#0EA5E9" x="12" y="9" height="1" width="1" />
        <rect fill="#F8FAFC" x="13" y="9" height="1" width="1" />
        <rect fill="#F8FAFC" x="14" y="9" height="1" width="1" />
        <rect fill="#F8FAFC" x="15" y="9" height="1" width="1" />
        <rect fill="#F8FAFC" x="0" y="10" height="1" width="1" />
        <rect fill="#F8FAFC" x="1" y="10" height="1" width="1" />
        <rect fill="#F8FAFC" x="2" y="10" height="1" width="1" />
        <rect fill="#F8FAFC" x="3" y="10" height="1" width="1" />
        <rect fill="#F8FAFC" x="4" y="10" height="1" width="1" />
        <rect fill="#F8FAFC" x="5" y="10" height="1" width="1" />
        <rect fill="#F8FAFC" x="6" y="10" height="1" width="1" />
        <rect fill="#F8FAFC" x="7" y="10" height="1" width="1" />
        <rect fill="#F8FAFC" x="8" y="10" height="1" width="1" />
        <rect fill="#F8FAFC" x="9" y="10" height="1" width="1" />
        <rect fill="#0EA5E9" x="10" y="10" height="1" width="1" />
        <rect fill="#0EA5E9" x="11" y="10" height="1" width="1" />
        <rect fill="#F8FAFC" x="12" y="10" height="1" width="1" />
        <rect fill="#F8FAFC" x="13" y="10" height="1" width="1" />
        <rect fill="#F8FAFC" x="14" y="10" height="1" width="1" />
        <rect fill="#F8FAFC" x="15" y="10" height="1" width="1" />
        <rect fill="#F8FAFC" x="0" y="11" height="1" width="1" />
        <rect fill="#F8FAFC" x="1" y="11" height="1" width="1" />
        <rect fill="#F8FAFC" x="2" y="11" height="1" width="1" />
        <rect fill="#F8FAFC" x="3" y="11" height="1" width="1" />
        <rect fill="#F8FAFC" x="4" y="11" height="1" width="1" />
        <rect fill="#F8FAFC" x="5" y="11" height="1" width="1" />
        <rect fill="#F8FAFC" x="6" y="11" height="1" width="1" />
        <rect fill="#F8FAFC" x="7" y="11" height="1" width="1" />
        <rect fill="#F8FAFC" x="8" y="11" height="1" width="1" />
        <rect fill="#0EA5E9" x="9" y="11" height="1" width="1" />
        <rect fill="#0EA5E9" x="10" y="11" height="1" width="1" />
        <rect fill="#F8FAFC" x="11" y="11" height="1" width="1" />
        <rect fill="#F8FAFC" x="12" y="11" height="1" width="1" />
        <rect fill="#F8FAFC" x="13" y="11" height="1" width="1" />
        <rect fill="#F8FAFC" x="14" y="11" height="1" width="1" />
        <rect fill="#F8FAFC" x="15" y="11" height="1" width="1" />
        <rect fill="#F8FAFC" x="0" y="12" height="1" width="1" />
        <rect fill="#F8FAFC" x="1" y="12" height="1" width="1" />
        <rect fill="#F8FAFC" x="2" y="12" height="1" width="1" />
        <rect fill="#F8FAFC" x="3" y="12" height="1" width="1" />
        <rect fill="#F8FAFC" x="4" y="12" height="1" width="1" />
        <rect fill="#F8FAFC" x="5" y="12" height="1" width="1" />
        <rect fill="#F8FAFC" x="6" y="12" height="1" width="1" />
        <rect fill="#F8FAFC" x="7" y="12" height="1" width="1" />
        <rect fill="#0EA5E9" x="8" y="12" height="1" width="1" />
        <rect fill="#0EA5E9" x="9" y="12" height="1" width="1" />
        <rect fill="#F8FAFC" x="10" y="12" height="1" width="1" />
        <rect fill="#F8FAFC" x="11" y="12" height="1" width="1" />
        <rect fill="#F8FAFC" x="12" y="12" height="1" width="1" />
        <rect fill="#F8FAFC" x="13" y="12" height="1" width="1" />
        <rect fill="#F8FAFC" x="14" y="12" height="1" width="1" />
        <rect fill="#F8FAFC" x="15" y="12" height="1" width="1" />
        <rect fill="#F8FAFC" x="0" y="13" height="1" width="1" />
        <rect fill="#F8FAFC" x="1" y="13" height="1" width="1" />
        <rect fill="#F8FAFC" x="2" y="13" height="1" width="1" />
        <rect fill="#F8FAFC" x="3" y="13" height="1" width="1" />
        <rect fill="#F8FAFC" x="4" y="13" height="1" width="1" />
        <rect fill="#F8FAFC" x="5" y="13" height="1" width="1" />
        <rect fill="#0EA5E9" x="6" y="13" height="1" width="1" />
        <rect fill="#0EA5E9" x="7" y="13" height="1" width="1" />
        <rect fill="#0EA5E9" x="8" y="13" height="1" width="1" />
        <rect fill="#F8FAFC" x="9" y="13" height="1" width="1" />
        <rect fill="#F8FAFC" x="10" y="13" height="1" width="1" />
        <rect fill="#F8FAFC" x="11" y="13" height="1" width="1" />
        <rect fill="#F8FAFC" x="12" y="13" height="1" width="1" />
        <rect fill="#F8FAFC" x="13" y="13" height="1" width="1" />
        <rect fill="#F8FAFC" x="14" y="13" height="1" width="1" />
        <rect fill="#F8FAFC" x="15" y="13" height="1" width="1" />
        <rect fill="#F8FAFC" x="0" y="14" height="1" width="1" />
        <rect fill="#F8FAFC" x="1" y="14" height="1" width="1" />
        <rect fill="#F8FAFC" x="2" y="14" height="1" width="1" />
        <rect fill="#F8FAFC" x="3" y="14" height="1" width="1" />
        <rect fill="#F8FAFC" x="4" y="14" height="1" width="1" />
        <rect fill="#0EA5E9" x="5" y="14" height="1" width="1" />
        <rect fill="#0EA5E9" x="6" y="14" height="1" width="1" />
        <rect fill="#F8FAFC" x="7" y="14" height="1" width="1" />
        <rect fill="#F8FAFC" x="8" y="14" height="1" width="1" />
        <rect fill="#F8FAFC" x="9" y="14" height="1" width="1" />
        <rect fill="#F8FAFC" x="10" y="14" height="1" width="1" />
        <rect fill="#F8FAFC" x="11" y="14" height="1" width="1" />
        <rect fill="#F8FAFC" x="12" y="14" height="1" width="1" />
        <rect fill="#F8FAFC" x="13" y="14" height="1" width="1" />
        <rect fill="#F8FAFC" x="14" y="14" height="1" width="1" />
        <rect fill="#F8FAFC" x="15" y="14" height="1" width="1" />
        <rect fill="#F8FAFC" x="0" y="15" height="1" width="1" />
        <rect fill="#F8FAFC" x="1" y="15" height="1" width="1" />
        <rect fill="#F8FAFC" x="2" y="15" height="1" width="1" />
        <rect fill="#F8FAFC" x="3" y="15" height="1" width="1" />
        <rect fill="#F8FAFC" x="4" y="15" height="1" width="1" />
        <rect fill="#F8FAFC" x="5" y="15" height="1" width="1" />
        <rect fill="#F8FAFC" x="6" y="15" height="1" width="1" />
        <rect fill="#F8FAFC" x="7" y="15" height="1" width="1" />
        <rect fill="#F8FAFC" x="8" y="15" height="1" width="1" />
        <rect fill="#F8FAFC" x="9" y="15" height="1" width="1" />
        <rect fill="#F8FAFC" x="10" y="15" height="1" width="1" />
        <rect fill="#F8FAFC" x="11" y="15" height="1" width="1" />
        <rect fill="#F8FAFC" x="12" y="15" height="1" width="1" />
        <rect fill="#F8FAFC" x="13" y="15" height="1" width="1" />
        <rect fill="#F8FAFC" x="14" y="15" height="1" width="1" />
        <rect fill="#F8FAFC" x="15" y="15" height="1" width="1" />
      </g>
    </svg>
  );

  const MoveLeftIcon = (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      shapeRendering="crispEdges"
      version="1.1"
      viewBox="0 0 256 256"
      className="h-8"
    >
      <g transform="scale(16 16)">
        <rect fill="#F8FAFC" x="0" y="0" height="1" width="1" />
        <rect fill="#F8FAFC" x="1" y="0" height="1" width="1" />
        <rect fill="#F8FAFC" x="2" y="0" height="1" width="1" />
        <rect fill="#F8FAFC" x="3" y="0" height="1" width="1" />
        <rect fill="#F8FAFC" x="4" y="0" height="1" width="1" />
        <rect fill="#F8FAFC" x="5" y="0" height="1" width="1" />
        <rect fill="#F8FAFC" x="6" y="0" height="1" width="1" />
        <rect fill="#F8FAFC" x="7" y="0" height="1" width="1" />
        <rect fill="#F8FAFC" x="8" y="0" height="1" width="1" />
        <rect fill="#F8FAFC" x="9" y="0" height="1" width="1" />
        <rect fill="#F8FAFC" x="10" y="0" height="1" width="1" />
        <rect fill="#F8FAFC" x="11" y="0" height="1" width="1" />
        <rect fill="#F8FAFC" x="12" y="0" height="1" width="1" />
        <rect fill="#F8FAFC" x="13" y="0" height="1" width="1" />
        <rect fill="#F8FAFC" x="14" y="0" height="1" width="1" />
        <rect fill="#F8FAFC" x="15" y="0" height="1" width="1" />
        <rect fill="#F8FAFC" x="0" y="1" height="1" width="1" />
        <rect fill="#F8FAFC" x="1" y="1" height="1" width="1" />
        <rect fill="#F8FAFC" x="2" y="1" height="1" width="1" />
        <rect fill="#F8FAFC" x="3" y="1" height="1" width="1" />
        <rect fill="#F8FAFC" x="4" y="1" height="1" width="1" />
        <rect fill="#F8FAFC" x="5" y="1" height="1" width="1" />
        <rect fill="#F8FAFC" x="6" y="1" height="1" width="1" />
        <rect fill="#F8FAFC" x="7" y="1" height="1" width="1" />
        <rect fill="#F8FAFC" x="8" y="1" height="1" width="1" />
        <rect fill="#0EA5E9" x="9" y="1" height="1" width="1" />
        <rect fill="#0EA5E9" x="10" y="1" height="1" width="1" />
        <rect fill="#F8FAFC" x="11" y="1" height="1" width="1" />
        <rect fill="#F8FAFC" x="12" y="1" height="1" width="1" />
        <rect fill="#F8FAFC" x="13" y="1" height="1" width="1" />
        <rect fill="#F8FAFC" x="14" y="1" height="1" width="1" />
        <rect fill="#F8FAFC" x="15" y="1" height="1" width="1" />
        <rect fill="#F8FAFC" x="0" y="2" height="1" width="1" />
        <rect fill="#F8FAFC" x="1" y="2" height="1" width="1" />
        <rect fill="#F8FAFC" x="2" y="2" height="1" width="1" />
        <rect fill="#F8FAFC" x="3" y="2" height="1" width="1" />
        <rect fill="#F8FAFC" x="4" y="2" height="1" width="1" />
        <rect fill="#F8FAFC" x="5" y="2" height="1" width="1" />
        <rect fill="#F8FAFC" x="6" y="2" height="1" width="1" />
        <rect fill="#F8FAFC" x="7" y="2" height="1" width="1" />
        <rect fill="#0EA5E9" x="8" y="2" height="1" width="1" />
        <rect fill="#0EA5E9" x="9" y="2" height="1" width="1" />
        <rect fill="#F8FAFC" x="10" y="2" height="1" width="1" />
        <rect fill="#F8FAFC" x="11" y="2" height="1" width="1" />
        <rect fill="#F8FAFC" x="12" y="2" height="1" width="1" />
        <rect fill="#F8FAFC" x="13" y="2" height="1" width="1" />
        <rect fill="#F8FAFC" x="14" y="2" height="1" width="1" />
        <rect fill="#F8FAFC" x="15" y="2" height="1" width="1" />
        <rect fill="#F8FAFC" x="0" y="3" height="1" width="1" />
        <rect fill="#F8FAFC" x="1" y="3" height="1" width="1" />
        <rect fill="#F8FAFC" x="2" y="3" height="1" width="1" />
        <rect fill="#F8FAFC" x="3" y="3" height="1" width="1" />
        <rect fill="#F8FAFC" x="4" y="3" height="1" width="1" />
        <rect fill="#F8FAFC" x="5" y="3" height="1" width="1" />
        <rect fill="#0EA5E9" x="6" y="3" height="1" width="1" />
        <rect fill="#0EA5E9" x="7" y="3" height="1" width="1" />
        <rect fill="#0EA5E9" x="8" y="3" height="1" width="1" />
        <rect fill="#F8FAFC" x="9" y="3" height="1" width="1" />
        <rect fill="#F8FAFC" x="10" y="3" height="1" width="1" />
        <rect fill="#F8FAFC" x="11" y="3" height="1" width="1" />
        <rect fill="#F8FAFC" x="12" y="3" height="1" width="1" />
        <rect fill="#F8FAFC" x="13" y="3" height="1" width="1" />
        <rect fill="#F8FAFC" x="14" y="3" height="1" width="1" />
        <rect fill="#F8FAFC" x="15" y="3" height="1" width="1" />
        <rect fill="#F8FAFC" x="0" y="4" height="1" width="1" />
        <rect fill="#F8FAFC" x="1" y="4" height="1" width="1" />
        <rect fill="#F8FAFC" x="2" y="4" height="1" width="1" />
        <rect fill="#F8FAFC" x="3" y="4" height="1" width="1" />
        <rect fill="#F8FAFC" x="4" y="4" height="1" width="1" />
        <rect fill="#0EA5E9" x="5" y="4" height="1" width="1" />
        <rect fill="#0EA5E9" x="6" y="4" height="1" width="1" />
        <rect fill="#F8FAFC" x="7" y="4" height="1" width="1" />
        <rect fill="#F8FAFC" x="8" y="4" height="1" width="1" />
        <rect fill="#F8FAFC" x="9" y="4" height="1" width="1" />
        <rect fill="#F8FAFC" x="10" y="4" height="1" width="1" />
        <rect fill="#F8FAFC" x="11" y="4" height="1" width="1" />
        <rect fill="#F8FAFC" x="12" y="4" height="1" width="1" />
        <rect fill="#F8FAFC" x="13" y="4" height="1" width="1" />
        <rect fill="#F8FAFC" x="14" y="4" height="1" width="1" />
        <rect fill="#F8FAFC" x="15" y="4" height="1" width="1" />
        <rect fill="#F8FAFC" x="0" y="5" height="1" width="1" />
        <rect fill="#F8FAFC" x="1" y="5" height="1" width="1" />
        <rect fill="#F8FAFC" x="2" y="5" height="1" width="1" />
        <rect fill="#F8FAFC" x="3" y="5" height="1" width="1" />
        <rect fill="#0EA5E9" x="4" y="5" height="1" width="1" />
        <rect fill="#0EA5E9" x="5" y="5" height="1" width="1" />
        <rect fill="#F8FAFC" x="6" y="5" height="1" width="1" />
        <rect fill="#F8FAFC" x="7" y="5" height="1" width="1" />
        <rect fill="#F8FAFC" x="8" y="5" height="1" width="1" />
        <rect fill="#F8FAFC" x="9" y="5" height="1" width="1" />
        <rect fill="#F8FAFC" x="10" y="5" height="1" width="1" />
        <rect fill="#F8FAFC" x="11" y="5" height="1" width="1" />
        <rect fill="#F8FAFC" x="12" y="5" height="1" width="1" />
        <rect fill="#F8FAFC" x="13" y="5" height="1" width="1" />
        <rect fill="#F8FAFC" x="14" y="5" height="1" width="1" />
        <rect fill="#F8FAFC" x="15" y="5" height="1" width="1" />
        <rect fill="#F8FAFC" x="0" y="6" height="1" width="1" />
        <rect fill="#F8FAFC" x="1" y="6" height="1" width="1" />
        <rect fill="#0EA5E9" x="2" y="6" height="1" width="1" />
        <rect fill="#0EA5E9" x="3" y="6" height="1" width="1" />
        <rect fill="#0EA5E9" x="4" y="6" height="1" width="1" />
        <rect fill="#F8FAFC" x="5" y="6" height="1" width="1" />
        <rect fill="#F8FAFC" x="6" y="6" height="1" width="1" />
        <rect fill="#F8FAFC" x="7" y="6" height="1" width="1" />
        <rect fill="#F8FAFC" x="8" y="6" height="1" width="1" />
        <rect fill="#F8FAFC" x="9" y="6" height="1" width="1" />
        <rect fill="#F8FAFC" x="10" y="6" height="1" width="1" />
        <rect fill="#F8FAFC" x="11" y="6" height="1" width="1" />
        <rect fill="#F8FAFC" x="12" y="6" height="1" width="1" />
        <rect fill="#F8FAFC" x="13" y="6" height="1" width="1" />
        <rect fill="#F8FAFC" x="14" y="6" height="1" width="1" />
        <rect fill="#F8FAFC" x="15" y="6" height="1" width="1" />
        <rect fill="#F8FAFC" x="0" y="7" height="1" width="1" />
        <rect fill="#0EA5E9" x="1" y="7" height="1" width="1" />
        <rect fill="#0EA5E9" x="2" y="7" height="1" width="1" />
        <rect fill="#F8FAFC" x="3" y="7" height="1" width="1" />
        <rect fill="#F8FAFC" x="4" y="7" height="1" width="1" />
        <rect fill="#F8FAFC" x="5" y="7" height="1" width="1" />
        <rect fill="#F8FAFC" x="6" y="7" height="1" width="1" />
        <rect fill="#F8FAFC" x="7" y="7" height="1" width="1" />
        <rect fill="#F8FAFC" x="8" y="7" height="1" width="1" />
        <rect fill="#F8FAFC" x="9" y="7" height="1" width="1" />
        <rect fill="#F8FAFC" x="10" y="7" height="1" width="1" />
        <rect fill="#F8FAFC" x="11" y="7" height="1" width="1" />
        <rect fill="#F8FAFC" x="12" y="7" height="1" width="1" />
        <rect fill="#F8FAFC" x="13" y="7" height="1" width="1" />
        <rect fill="#F8FAFC" x="14" y="7" height="1" width="1" />
        <rect fill="#F8FAFC" x="15" y="7" height="1" width="1" />
        <rect fill="#F8FAFC" x="0" y="8" height="1" width="1" />
        <rect fill="#F8FAFC" x="1" y="8" height="1" width="1" />
        <rect fill="#0EA5E9" x="2" y="8" height="1" width="1" />
        <rect fill="#0EA5E9" x="3" y="8" height="1" width="1" />
        <rect fill="#F8FAFC" x="4" y="8" height="1" width="1" />
        <rect fill="#F8FAFC" x="5" y="8" height="1" width="1" />
        <rect fill="#F8FAFC" x="6" y="8" height="1" width="1" />
        <rect fill="#F8FAFC" x="7" y="8" height="1" width="1" />
        <rect fill="#F8FAFC" x="8" y="8" height="1" width="1" />
        <rect fill="#F8FAFC" x="9" y="8" height="1" width="1" />
        <rect fill="#F8FAFC" x="10" y="8" height="1" width="1" />
        <rect fill="#F8FAFC" x="11" y="8" height="1" width="1" />
        <rect fill="#F8FAFC" x="12" y="8" height="1" width="1" />
        <rect fill="#F8FAFC" x="13" y="8" height="1" width="1" />
        <rect fill="#F8FAFC" x="14" y="8" height="1" width="1" />
        <rect fill="#F8FAFC" x="15" y="8" height="1" width="1" />
        <rect fill="#F8FAFC" x="0" y="9" height="1" width="1" />
        <rect fill="#F8FAFC" x="1" y="9" height="1" width="1" />
        <rect fill="#F8FAFC" x="2" y="9" height="1" width="1" />
        <rect fill="#0EA5E9" x="3" y="9" height="1" width="1" />
        <rect fill="#0EA5E9" x="4" y="9" height="1" width="1" />
        <rect fill="#F8FAFC" x="5" y="9" height="1" width="1" />
        <rect fill="#F8FAFC" x="6" y="9" height="1" width="1" />
        <rect fill="#F8FAFC" x="7" y="9" height="1" width="1" />
        <rect fill="#F8FAFC" x="8" y="9" height="1" width="1" />
        <rect fill="#F8FAFC" x="9" y="9" height="1" width="1" />
        <rect fill="#F8FAFC" x="10" y="9" height="1" width="1" />
        <rect fill="#F8FAFC" x="11" y="9" height="1" width="1" />
        <rect fill="#F8FAFC" x="12" y="9" height="1" width="1" />
        <rect fill="#F8FAFC" x="13" y="9" height="1" width="1" />
        <rect fill="#F8FAFC" x="14" y="9" height="1" width="1" />
        <rect fill="#F8FAFC" x="15" y="9" height="1" width="1" />
        <rect fill="#F8FAFC" x="0" y="10" height="1" width="1" />
        <rect fill="#F8FAFC" x="1" y="10" height="1" width="1" />
        <rect fill="#F8FAFC" x="2" y="10" height="1" width="1" />
        <rect fill="#F8FAFC" x="3" y="10" height="1" width="1" />
        <rect fill="#0EA5E9" x="4" y="10" height="1" width="1" />
        <rect fill="#0EA5E9" x="5" y="10" height="1" width="1" />
        <rect fill="#0EA5E9" x="6" y="10" height="1" width="1" />
        <rect fill="#F8FAFC" x="7" y="10" height="1" width="1" />
        <rect fill="#F8FAFC" x="8" y="10" height="1" width="1" />
        <rect fill="#F8FAFC" x="9" y="10" height="1" width="1" />
        <rect fill="#F8FAFC" x="10" y="10" height="1" width="1" />
        <rect fill="#F8FAFC" x="11" y="10" height="1" width="1" />
        <rect fill="#F8FAFC" x="12" y="10" height="1" width="1" />
        <rect fill="#F8FAFC" x="13" y="10" height="1" width="1" />
        <rect fill="#F8FAFC" x="14" y="10" height="1" width="1" />
        <rect fill="#F8FAFC" x="15" y="10" height="1" width="1" />
        <rect fill="#F8FAFC" x="0" y="11" height="1" width="1" />
        <rect fill="#F8FAFC" x="1" y="11" height="1" width="1" />
        <rect fill="#F8FAFC" x="2" y="11" height="1" width="1" />
        <rect fill="#F8FAFC" x="3" y="11" height="1" width="1" />
        <rect fill="#F8FAFC" x="4" y="11" height="1" width="1" />
        <rect fill="#F8FAFC" x="5" y="11" height="1" width="1" />
        <rect fill="#0EA5E9" x="6" y="11" height="1" width="1" />
        <rect fill="#0EA5E9" x="7" y="11" height="1" width="1" />
        <rect fill="#F8FAFC" x="8" y="11" height="1" width="1" />
        <rect fill="#F8FAFC" x="9" y="11" height="1" width="1" />
        <rect fill="#F8FAFC" x="10" y="11" height="1" width="1" />
        <rect fill="#F8FAFC" x="11" y="11" height="1" width="1" />
        <rect fill="#F8FAFC" x="12" y="11" height="1" width="1" />
        <rect fill="#F8FAFC" x="13" y="11" height="1" width="1" />
        <rect fill="#F8FAFC" x="14" y="11" height="1" width="1" />
        <rect fill="#F8FAFC" x="15" y="11" height="1" width="1" />
        <rect fill="#F8FAFC" x="0" y="12" height="1" width="1" />
        <rect fill="#F8FAFC" x="1" y="12" height="1" width="1" />
        <rect fill="#F8FAFC" x="2" y="12" height="1" width="1" />
        <rect fill="#F8FAFC" x="3" y="12" height="1" width="1" />
        <rect fill="#F8FAFC" x="4" y="12" height="1" width="1" />
        <rect fill="#F8FAFC" x="5" y="12" height="1" width="1" />
        <rect fill="#F8FAFC" x="6" y="12" height="1" width="1" />
        <rect fill="#0EA5E9" x="7" y="12" height="1" width="1" />
        <rect fill="#0EA5E9" x="8" y="12" height="1" width="1" />
        <rect fill="#F8FAFC" x="9" y="12" height="1" width="1" />
        <rect fill="#F8FAFC" x="10" y="12" height="1" width="1" />
        <rect fill="#F8FAFC" x="11" y="12" height="1" width="1" />
        <rect fill="#F8FAFC" x="12" y="12" height="1" width="1" />
        <rect fill="#F8FAFC" x="13" y="12" height="1" width="1" />
        <rect fill="#F8FAFC" x="14" y="12" height="1" width="1" />
        <rect fill="#F8FAFC" x="15" y="12" height="1" width="1" />
        <rect fill="#F8FAFC" x="0" y="13" height="1" width="1" />
        <rect fill="#F8FAFC" x="1" y="13" height="1" width="1" />
        <rect fill="#F8FAFC" x="2" y="13" height="1" width="1" />
        <rect fill="#F8FAFC" x="3" y="13" height="1" width="1" />
        <rect fill="#F8FAFC" x="4" y="13" height="1" width="1" />
        <rect fill="#F8FAFC" x="5" y="13" height="1" width="1" />
        <rect fill="#F8FAFC" x="6" y="13" height="1" width="1" />
        <rect fill="#F8FAFC" x="7" y="13" height="1" width="1" />
        <rect fill="#0EA5E9" x="8" y="13" height="1" width="1" />
        <rect fill="#0EA5E9" x="9" y="13" height="1" width="1" />
        <rect fill="#F8FAFC" x="10" y="13" height="1" width="1" />
        <rect fill="#F8FAFC" x="11" y="13" height="1" width="1" />
        <rect fill="#F8FAFC" x="12" y="13" height="1" width="1" />
        <rect fill="#F8FAFC" x="13" y="13" height="1" width="1" />
        <rect fill="#F8FAFC" x="14" y="13" height="1" width="1" />
        <rect fill="#F8FAFC" x="15" y="13" height="1" width="1" />
        <rect fill="#F8FAFC" x="0" y="14" height="1" width="1" />
        <rect fill="#F8FAFC" x="1" y="14" height="1" width="1" />
        <rect fill="#F8FAFC" x="2" y="14" height="1" width="1" />
        <rect fill="#F8FAFC" x="3" y="14" height="1" width="1" />
        <rect fill="#F8FAFC" x="4" y="14" height="1" width="1" />
        <rect fill="#F8FAFC" x="5" y="14" height="1" width="1" />
        <rect fill="#F8FAFC" x="6" y="14" height="1" width="1" />
        <rect fill="#F8FAFC" x="7" y="14" height="1" width="1" />
        <rect fill="#F8FAFC" x="8" y="14" height="1" width="1" />
        <rect fill="#0EA5E9" x="9" y="14" height="1" width="1" />
        <rect fill="#0EA5E9" x="10" y="14" height="1" width="1" />
        <rect fill="#F8FAFC" x="11" y="14" height="1" width="1" />
        <rect fill="#F8FAFC" x="12" y="14" height="1" width="1" />
        <rect fill="#F8FAFC" x="13" y="14" height="1" width="1" />
        <rect fill="#F8FAFC" x="14" y="14" height="1" width="1" />
        <rect fill="#F8FAFC" x="15" y="14" height="1" width="1" />
        <rect fill="#F8FAFC" x="0" y="15" height="1" width="1" />
        <rect fill="#F8FAFC" x="1" y="15" height="1" width="1" />
        <rect fill="#F8FAFC" x="2" y="15" height="1" width="1" />
        <rect fill="#F8FAFC" x="3" y="15" height="1" width="1" />
        <rect fill="#F8FAFC" x="4" y="15" height="1" width="1" />
        <rect fill="#F8FAFC" x="5" y="15" height="1" width="1" />
        <rect fill="#F8FAFC" x="6" y="15" height="1" width="1" />
        <rect fill="#F8FAFC" x="7" y="15" height="1" width="1" />
        <rect fill="#F8FAFC" x="8" y="15" height="1" width="1" />
        <rect fill="#F8FAFC" x="9" y="15" height="1" width="1" />
        <rect fill="#F8FAFC" x="10" y="15" height="1" width="1" />
        <rect fill="#F8FAFC" x="11" y="15" height="1" width="1" />
        <rect fill="#F8FAFC" x="12" y="15" height="1" width="1" />
        <rect fill="#F8FAFC" x="13" y="15" height="1" width="1" />
        <rect fill="#F8FAFC" x="14" y="15" height="1" width="1" />
        <rect fill="#F8FAFC" x="15" y="15" height="1" width="1" />
      </g>
    </svg>
  );

  if (skinItem == "dropper") {
    return DropperIcon;
  } else if (skinItem == "dropper-active") {
    return DropperIconActive;
  } else if (skinItem == "move-up") {
    return MoveUpIcon;
  } else if (skinItem == "move-down") {
    return MoveDownIcon;
  } else if (skinItem == "move-right") {
    return MoveRightIcon;
  } else if (skinItem == "move-left") {
    return MoveLeftIcon;
  }
  return null;
};
